/* eslint-disable perfectionist/sort-objects */
// Logical sidebar groups for sections with many flat feature pages — declaration order is the display
// Order, membership is by page slug. Sections without an entry render their pages ungrouped (alphabetical
// Is enough below ~6 pages), and roadmap/deferred/rejected always trail in an automatic Planning group.
export const DocsSectionGroupsMap: Readonly<Record<string, Readonly<Record<string, readonly string[]>>>> = {
  architecture: {
    "Core standards": [
      "platform",
      "resources",
      "datasets",
      "publishing",
      "serialization",
      "client-data",
      "async-operations",
      "caching",
      "persisted-data-latest-shape-only",
      "content-token-rewriting",
      "dialog-shell",
      "destructive-confirmation",
      "persist-then-notify",
      "conditional-writes",
      "blob-lifecycle",
      "no-polling",
      "no-manual-recovery",
      "null-vs-undefined",
      "module-boundaries",
      "singleton-dialogs",
      "navigation",
      "search",
    ],
    Backend: ["auth", "rate-limiting", "azure-services", "file-uploads"],
    Development: ["environment", "monorepo-tooling", "server-testing"],
    Frontend: ["responsive", "security-posture"],
  },
  esbabbler: {
    Messaging: [
      "messaging",
      "message-list-rendering",
      "room-ui",
      "mention-badges",
      "slash-commands",
      "scheduled-messages",
      "drafts-and-sent",
      "thread-follows",
      "file-media",
    ],
    "Members & profiles": [
      "friends-and-dms",
      "profiles-and-presence",
      "nicknames",
      "invites",
      "settings",
      "room-settings",
    ],
    Moderation: ["moderation", "automod-actions", "moderator-notes", "rbac"],
    Calls: ["voice-video", "push-to-talk", "calls"],
    Infrastructure: ["push-notifications", "offline-cache", "webhooks"],
  },
  platform: {
    "Explorer & shell": [
      "resource-explorer",
      "resource-service-menu",
      "list-filters-and-views",
      "summary-view",
      "resource-page-parity",
      "share-to-esbabbler",
      "notifications",
      "todolist-due-reminders",
      "global-search",
      "global-search-relevance",
      "favorites-and-recents",
      "tags",
      "recycle-bin",
      "activity-log",
      "publish-history",
      "shell-cohesion",
      "breadcrumb-trail",
    ],
    Resources: [
      "sheet-resource",
      "create-from-file",
      "survey-resource",
      "program-resource",
      "note-resource",
      "blueprint-resource",
      "blueprint-capture",
      "resource-file-assets",
      "storage-quotas",
    ],
    "Survey funnel": [
      "survey-response-controls",
      "survey-response-modes",
      "survey-response-management",
      "published-view-analytics",
    ],
    Editors: [
      "dashboard-data-binding",
      "email-personalization",
      "email-web-view",
      "flowchart-publish",
      "webpage-survey-invite-blocks",
      "dataset-row-cap-warning",
    ],
  },
  virrun: {
    Core: ["architecture", "orchestrator-api", "execution-backends", "configuration"],
    Performance: ["cache", "task-cache", "task-cache-eviction", "snapshot-and-fork", "write-back", "wsl-source-mirror"],
    Guarantees: ["correctness", "benchmarking", "subprocess-timeouts", "derived-not-named"],
    Background: ["adoption", "prior-art"],
  },
};
