import type { SkyState } from "genshin-engine";

import { LoginTimeOfDay } from "#src/models/login/LoginTimeOfDay";
import { Color, Vector3 } from "three";

// Each time of day's sky and light, its colours read off its reference: the gradient's zenith and horizon, the haze
// Over the cloud sea (the mean of its brightest two samples low in the frame), the clouds,
// And where the light comes from, which is from the left in all four (low at dawn and dusk, and the moon's at night)
export const LoginSkyStateMap: Record<LoginTimeOfDay, SkyState> = {
  [LoginTimeOfDay.Dawn]: {
    cloudLitColor: new Color(0xf2dfc8),
    cloudShadeColor: new Color(0x8c91a7),
    fogColor: new Color(0xe9d8c7),
    hemisphereGroundColor: new Color(0xf2dfc8),
    hemisphereIntensity: 1.1,
    hemisphereSkyColor: new Color(0x8c91a7),
    horizonColor: new Color(0xf2c9a4),
    lightColor: new Color(0xffd8a8),
    lightDirection: new Vector3(-0.951, 0.08, -0.3).normalize(),
    lightIntensity: 1.3,
    moonDirection: new Vector3(0.951, -0.08, 0.3).normalize(),
    starIntensity: 0,
    sunDirection: new Vector3(-0.951, 0.08, -0.3).normalize(),
    zenithColor: new Color(0x42608c),
  },
  [LoginTimeOfDay.Day]: {
    cloudLitColor: new Color(0xffffff),
    cloudShadeColor: new Color(0xb8cbe0),
    fogColor: new Color(0xceddee),
    hemisphereGroundColor: new Color(0xd4e4ef),
    hemisphereIntensity: 1.3,
    hemisphereSkyColor: new Color(0x9ec0e8),
    horizonColor: new Color(0xb0c9e3),
    lightColor: new Color(0xfff4e6),
    lightDirection: new Vector3(-0.526, 0.789, -0.316).normalize(),
    lightIntensity: 1.5,
    moonDirection: new Vector3(0.526, -0.789, 0.316).normalize(),
    starIntensity: 0,
    sunDirection: new Vector3(-0.526, 0.789, -0.316).normalize(),
    zenithColor: new Color(0x3b68a0),
  },
  [LoginTimeOfDay.Dusk]: {
    cloudLitColor: new Color(0xfcdbad),
    cloudShadeColor: new Color(0xa9708d),
    fogColor: new Color(0xf0c4aa),
    hemisphereGroundColor: new Color(0xfcdbad),
    hemisphereIntensity: 1.1,
    hemisphereSkyColor: new Color(0xa9708d),
    horizonColor: new Color(0xf2b08a),
    lightColor: new Color(0xffc890),
    lightDirection: new Vector3(-0.902, 0.251, -0.351).normalize(),
    lightIntensity: 1.3,
    moonDirection: new Vector3(0.902, -0.251, 0.351).normalize(),
    starIntensity: 0,
    sunDirection: new Vector3(-0.902, 0.251, -0.351).normalize(),
    zenithColor: new Color(0x7e5485),
  },
  [LoginTimeOfDay.Night]: {
    cloudLitColor: new Color(0x56b0f5),
    cloudShadeColor: new Color(0x255abb),
    fogColor: new Color(0x5ab4f8),
    hemisphereGroundColor: new Color(0x2d6fd0),
    hemisphereIntensity: 1,
    hemisphereSkyColor: new Color(0x2a4aa8),
    horizonColor: new Color(0x1f51c6),
    lightColor: new Color(0x9cc8ff),
    lightDirection: new Vector3(-0.551, 0.451, -0.702).normalize(),
    lightIntensity: 0.9,
    moonDirection: new Vector3(-0.551, 0.451, -0.702).normalize(),
    starIntensity: 1,
    sunDirection: new Vector3(0.551, -0.451, 0.702).normalize(),
    zenithColor: new Color(0x172161),
  },
};
