import { SITE_NAME } from "@/services/app/constants";

export const RoutePath = {
  About: "/about",
  Achievements: "/achievements",
  Anime: "/anime",
  Calls: (id: string) => `/calls/${id}`,
  CallsIndex: "/calls",
  Clicker: "/clicker",
  Docs: "/docs",
  Dungeons: "/dungeons",
  FluidSimulator: "/fluid-simulator",
  Github: `https://github.com/${SITE_NAME}/${SITE_NAME}`,
  Index: "/",
  Login: "/login",
  Messages: (id: string) => `/messages/${id}`,
  MessagesDraftsAndSent: "/messages/draftsandsent",
  MessagesFriends: "/messages/friends",
  MessagesIndex: "/messages",
  MessagesInvite: (code: string) => `/messages/invite/${code}`,
  MessagesMessage: (id: string, rowKey: string) => `/messages/${id}/${rowKey}`,
  Post: (id: string) => `/post/${id}`,
  PostCreate: "/post/create",
  PostUpdate: (id: string) => `/post/update/${id}`,
  PrivacyPolicy: "/privacy-policy",
  Resource: (id: string) => `/resources/${id}`,
  Resources: "/resources",
  ResourcesAll: "/resources/all",
  ResourcesCreate: "/resources/create",
  ResourcesCreateType: (type: string) => `/resources/create/${type}`,
  UserSettings: "/user/settings",
  View: (type: string, id: string) => `/view/${type}/${id}`,
} as const;
export type RoutePath = typeof RoutePath;
