FROM node:26.0.0-alpine
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

WORKDIR /app

COPY **/package.json pnpm-*.yaml ./
RUN pnpm fetch

COPY . .
WORKDIR /app/packages/app

RUN pnpm i --frozen-lockfile --offline

EXPOSE 3000
