packages:
  - packages/*

catalog:
  "@azure/core-http-compat": ^2.3.1
  "@azure/core-rest-pipeline": ^1.22.1
  "@azure/data-tables": ^13.3.1
  "@azure/search-documents": ^12.1.0
  "@azure/storage-blob": ^12.28.0
  "@codemirror/lang-vue": ^0.1.3
  "@codemirror/language": ^6.11.3
  "@codemirror/language-data": ^6.5.1
  "@codemirror/state": ^6.5.2
  "@codemirror/theme-one-dark": ^6.1.3
  "@codemirror/view": ^6.38.2
  "@electric-sql/pglite": ^0.3.8
  "@floating-ui/dom": ^1.7.4
  "@fullcalendar/core": ^6.1.19
  "@fullcalendar/daygrid": ^6.1.19
  "@fullcalendar/interaction": ^6.1.19
  "@fullcalendar/timegrid": ^6.1.19
  "@fullcalendar/vue3": ^6.1.19
  "@koumoul/vjsf": ^3.20.5
  "@lerna-lite/cli": ^4.7.3
  "@lerna-lite/publish": ^4.7.3
  "@lerna-lite/run": ^4.7.3
  "@mdi/font": ^7.4.47
  "@nuxt/eslint": ^1.9.0
  "@nuxt/fonts": ^0.11.4
  "@nuxt/scripts": ^0.11.13
  "@nuxt/test-utils": ^3.19.2
  "@nuxtjs/seo": ^3.1.0
  "@pinia/nuxt": ^0.11.2
  "@prettier/plugin-oxc": ^0.0.4
  "@tiptap/core": ^3.4.3
  "@tiptap/extension-file-handler": ^3.4.3
  "@tiptap/extension-mention": ^3.4.3
  "@tiptap/extensions": ^3.4.3
  "@tiptap/pm": ^3.4.3
  "@tiptap/starter-kit": ^3.4.3
  "@tiptap/suggestion": ^3.4.3
  "@tiptap/vue-3": ^3.4.3
  "@trpc/client": ^11.5.1
  "@trpc/server": ^11.5.1
  "@types/data-urls": ^3.0.4
  "@types/dedent": ^0.7.2
  "@types/deep-equal": ^1.0.4
  "@types/fs-extra": ^11.0.4
  "@types/howler": ^2.2.12
  "@types/js-beautify": ^1.14.3
  "@types/mjml-browser": ^4.15.0
  "@types/node": ^24.4.0
  "@types/omit-deep-lodash": ^1.1.3
  "@types/pluralize": ^0.0.33
  "@types/sax": ^1.2.7
  "@types/three": ^0.180.0
  "@types/web-push": ^3.6.4
  "@types/ws": ^8.18.1
  "@types/xml2js": ^0.4.14
  "@unocss/eslint-config": ^66.5.1
  "@unocss/nuxt": ^66.5.1
  "@vite-pwa/nuxt": ^1.0.4
  "@vitejs/plugin-vue": ^6.0.1
  "@vitest/coverage-v8": ^3.2.4
  "@vitest/eslint-plugin": ^1.3.10
  "@vue-flow/background": ^1.3.2
  "@vue-flow/controls": ^1.1.3
  "@vue-flow/core": ^1.46.4
  "@vue-flow/minimap": ^1.5.4
  "@vue-flow/node-resizer": ^1.5.0
  "@vue-pdf-viewer/viewer": ^3.0.0
  "@vue/language-core": ^3.0.7
  "@vue/test-utils": ^2.4.6
  "@vuepic/vue-datepicker": ^11.0.2
  "@vueuse/core": ^13.9.0
  "@vueuse/nuxt": ^13.9.0
  ajv: ^8.17.1
  ajv-errors: ^3.0.0
  ajv-formats: ^3.0.1
  ajv-i18n: ^4.2.0
  apexcharts: ^5.3.5
  better-auth: ^1.3.9
  codemirror: ^6.0.2
  ctix: ^2.7.1
  data-urls: ^6.0.0
  dayjs: ^1.11.18
  debug: ^4.4.3
  dedent: ^1.7.0
  defu: ^6.1.4
  dotenv: ^17.2.2
  drizzle-kit: ^0.31.4
  drizzle-orm: ^0.44.5
  drizzle-zod: ^0.8.3
  emoji-mart-vue-fast: ^15.0.5
  eslint: ^9.35.0
  eslint-config-prettier: ^10.1.8
  eslint-plugin-oxlint: ^1.15.0
  eslint-plugin-perfectionist: ^4.15.0
  eslint-plugin-pinia: ^0.4.1
  eslint-plugin-prettier: ^5.5.4
  eventemitter3: ^5.0.1
  events: ^3.3.0
  fast-deep-equal: ^3.1.3
  filesize: ^11.0.2
  fs-extra: ^11.3.1
  fuse.js: ^7.1.0
  grapesjs: ^0.22.12
  grapesjs-blocks-basic: ^1.0.2
  grapesjs-component-countdown: ^1.0.2
  grapesjs-custom-code: ^1.0.2
  grapesjs-mjml: ^1.0.7
  grapesjs-parser-postcss: ^1.0.3
  grapesjs-plugin-export: ^1.0.12
  grapesjs-plugin-forms: ^2.0.6
  grapesjs-preset-webpage: ^1.0.3
  grapesjs-style-bg: ^2.0.2
  grapesjs-tabs: ^1.0.6
  grapesjs-tooltip: ^0.1.8
  grapesjs-touch: ^0.1.1
  grapesjs-tui-image-editor: ^1.0.2
  grapesjs-typed: ^2.0.1
  grid-engine: ^2.48.1
  grid-layout-plus: ^1.1.0
  gsap: ^3.13.0
  h3: ^1.15.4
  happy-dom: ^18.0.1
  howler: ^2.2.4
  is-mobile: ^5.0.0
  js-beautify: ^1.15.4
  link-preview-js: ^3.1.0
  linkifyjs: ^4.3.2
  marked: ^16.3.0
  mjml-browser: ^4.15.3
  node-emoji: ^2.2.0
  node-html-parser: ^7.0.1
  nuxt: ^4.1.2
  nuxt-security: ^2.4.0
  obscenity: ^0.4.5
  omit-deep-lodash: ^1.1.7
  oxlint: ^1.15.0
  p-progress: ^1.0.0
  pathe: ^2.0.3
  pdfjs-dist: ^5.4.149
  phaser: ^4.0.0-rc.5
  phaser3-rex-plugins: ^1.80.16
  pinia: ^3.0.3
  pluralize: ^8.0.0
  postgres: ^3.4.7
  prettier: ^3.6.2
  rate-limiter-flexible: ^7.3.1
  rolldown: ^1.0.0-beta.38
  rolldown-plugin-dts: ^0.16.5
  rxjs: ^7.8.2
  sass-embedded: ^1.92.1
  sax: ^1.4.1
  show-open-file-picker: ^0.4.0
  sql-highlight: ^6.1.0
  superjson: ^2.2.2
  survey-core: ^2.3.6
  survey-creator-core: ^2.3.6
  survey-creator-vue: ^2.3.6
  survey-vue3-ui: ^2.3.6
  three: ^0.180.0
  three-globe: ^2.44.0
  trpc-nuxt: ^1.2.0
  tsx: ^4.20.5
  type-fest: ^5.0.0
  typedoc: ^0.28.13
  typescript: ^5.9.2
  typescript-eslint: ^8.43.0
  unocss: ^66.5.1
  unplugin-auto-import: ^20.1.0
  v-viewer: ^3.0.22
  viewerjs: ^1.11.7
  vite: npm:rolldown-vite@7.1.9
  vite-plugin-dts: ^4.5.4
  vite-plugin-mkcert: ^1.17.8
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.2.4
  vue: ^3.5.21
  vue-codemirror: ^6.1.1
  vue-pdf-embed: ^2.1.3
  vue-router: ^4.5.1
  vue-tsc: ^3.0.7
  vue3-apexcharts: ^1.8.0
  vuetify: ^3.10.0
  vuetify-nuxt-module: ^0.18.7
  web-push: ^3.6.7
  worker-timers: ^8.0.24
  ws: ^8.18.3
  xmlbuilder2: ^3.1.1
  zod: ^4.1.8

catalogMode: strict

onlyBuiltDependencies:
  - "@parcel/watcher"
  - core-js
  - esbuild
  - unrs-resolver
  - vue-demi

overrides:
  pdfjs-dist: ^5.4.149
  vite: npm:rolldown-vite@7.1.9

shellEmulator: true
