packages:
  - packages/*

catalog:
  "@azure/core-http-compat": ^2.3.1
  "@azure/core-rest-pipeline": ^1.22.2
  "@azure/data-tables": ^13.3.2
  "@azure/eventgrid": ^5.12.0
  "@azure/functions": ^4.10.0
  "@azure/identity": ^4.13.0
  "@azure/search-documents": ^12.2.0
  "@azure/storage-blob": ^12.29.1
  "@azure/storage-queue": ^12.28.1
  "@azure/web-pubsub": ^1.2.0
  "@azure/web-pubsub-client": ^1.0.2
  "@codemirror/lang-vue": ^0.1.3
  "@codemirror/language": ^6.11.3
  "@codemirror/language-data": ^6.5.2
  "@codemirror/state": ^6.5.2
  "@codemirror/theme-one-dark": ^6.1.3
  "@codemirror/view": ^6.39.4
  "@electric-sql/pglite": ^0.3.14
  "@eslint/core": ^1.0.0
  "@eslint/json": ^0.14.0
  "@floating-ui/dom": ^1.7.4
  "@fullcalendar/core": ^6.1.19
  "@fullcalendar/daygrid": ^6.1.19
  "@fullcalendar/interaction": ^6.1.19
  "@fullcalendar/timegrid": ^6.1.19
  "@fullcalendar/vue3": ^6.1.19
  "@koumoul/vjsf": ^3.25.5
  "@lerna-lite/cli": ^4.10.2
  "@lerna-lite/publish": ^4.10.2
  "@lerna-lite/run": ^4.10.2
  "@lerna-lite/watch": ^4.10.2
  "@mdi/font": ^7.4.47
  "@nuxt/eslint": ^1.12.1
  "@nuxt/fonts": ^0.12.1
  "@nuxt/hints": ^1.0.0-alpha.4
  "@nuxt/scripts": ^0.13.2
  "@nuxt/test-utils": ^3.21.0
  "@nuxtjs/seo": ^3.3.0
  "@pinia/nuxt": ^0.11.3
  "@prettier/plugin-oxc": ^0.1.3
  "@tiptap/core": ^3.14.0
  "@tiptap/extension-file-handler": ^3.14.0
  "@tiptap/extension-mention": ^3.14.0
  "@tiptap/extensions": ^3.14.0
  "@tiptap/pm": ^3.14.0
  "@tiptap/starter-kit": ^3.14.0
  "@tiptap/suggestion": ^3.14.0
  "@tiptap/vue-3": ^3.14.0
  "@trpc/client": ^11.8.1
  "@trpc/server": ^11.8.1
  "@types/data-urls": ^3.0.4
  "@types/dedent": ^0.7.2
  "@types/deep-equal": ^1.0.4
  "@types/fs-extra": ^11.0.4
  "@types/howler": ^2.2.12
  "@types/js-beautify": ^1.14.3
  "@types/mime-types": ^3.0.1
  "@types/mjml-browser": ^4.15.0
  "@types/node": ^25.0.3
  "@types/omit-deep-lodash": ^1.1.3
  "@types/pluralize": ^0.0.33
  "@types/sax": ^1.2.7
  "@types/three": ^0.182.0
  "@types/web-push": ^3.6.4
  "@types/ws": ^8.18.1
  "@types/xml2js": ^0.4.14
  "@unocss/eslint-config": ^66.5.10
  "@unocss/nuxt": ^66.5.10
  "@vite-pwa/nuxt": ^1.1.0
  "@vitejs/plugin-vue": ^6.0.3
  "@vitest/coverage-v8": ^4.0.16
  "@vitest/eslint-plugin": ^1.5.4
  "@vue-flow/background": ^1.3.2
  "@vue-flow/controls": ^1.1.3
  "@vue-flow/core": ^1.48.1
  "@vue-flow/minimap": ^1.5.4
  "@vue-flow/node-resizer": ^1.5.0
  "@vue-pdf-viewer/viewer": ^3.5.2
  "@vue/language-core": ^3.2.0
  "@vue/test-utils": ^2.4.6
  "@vuepic/vue-datepicker": ^12.1.0
  "@vueuse/core": ^14.1.0
  "@vueuse/nuxt": ^14.1.0
  ajv: ^8.17.1
  ajv-errors: ^3.0.0
  ajv-formats: ^3.0.1
  ajv-i18n: ^4.2.0
  apexcharts: ^5.3.6
  better-auth: ^1.4.7
  codemirror: ^6.0.2
  ctix: ^2.7.2
  data-urls: ^6.0.0
  dayjs: ^1.11.19
  debug: ^4.4.3
  dedent: ^1.7.1
  defu: ^6.1.4
  dotenv: ^17.2.3
  drizzle-kit: ^0.31.8
  drizzle-orm: ^0.45.1
  drizzle-zod: ^0.8.3
  emoji-mart-vue-fast: ^15.0.5
  eslint: ^9.39.2
  eslint-config-prettier: ^10.1.8
  eslint-plugin-depend: ^1.4.0
  eslint-plugin-oxlint: ^1.34.0
  eslint-plugin-perfectionist: ^5.0.0
  eslint-plugin-pinia: ^0.4.2
  eslint-plugin-prettier: ^5.5.4
  eventemitter3: ^5.0.1
  fast-deep-equal: ^3.1.3
  filesize: ^11.0.13
  fs-extra: ^11.3.3
  fuse.js: ^7.1.0
  grapesjs: ^0.22.14
  grapesjs-blocks-basic: ^1.0.2
  grapesjs-component-countdown: ^1.0.2
  grapesjs-custom-code: ^1.0.2
  grapesjs-mjml: ^1.0.7
  grapesjs-parser-postcss: ^1.0.3
  grapesjs-plugin-export: ^1.0.12
  grapesjs-plugin-forms: ^2.0.6
  grapesjs-preset-webpage: ^1.0.3
  grapesjs-style-bg: ^2.0.2
  grapesjs-tabs: ^1.0.6
  grapesjs-tooltip: ^0.1.8
  grapesjs-touch: ^0.1.1
  grapesjs-tui-image-editor: ^1.0.2
  grapesjs-typed: ^2.0.1
  grid-engine: ^2.48.2
  grid-layout-plus: ^1.1.1
  gsap: ^3.14.2
  h3: ^1.15.4
  happy-dom: ^20.0.11
  howler: ^2.2.4
  is-mobile: ^5.0.0
  js-beautify: ^1.15.4
  link-preview-js: ^4.0.0
  linkifyjs: ^4.3.2
  marked: ^17.0.1
  mime-types: ^3.0.2
  mjml-browser: ^4.18.0
  node-emoji: ^2.2.0
  node-html-parser: ^7.0.1
  nuxt: ^4.2.2
  nuxt-security: ^2.5.0
  obscenity: ^0.4.5
  omit-deep-lodash: ^1.1.7
  oxlint: ^1.34.0
  p-progress: ^1.0.0
  pathe: ^2.0.3
  pdfjs-dist: ^5.4.449
  phaser: ^4.0.0-rc.5
  phaser3-rex-plugins: ^1.80.17
  pinia: ^3.0.4
  pluralize: ^8.0.0
  postgres: ^3.4.7
  prettier: ^3.7.4
  prosemirror-state: ^1.4.4
  rate-limiter-flexible: ^9.0.1
  rolldown: ^1.0.0-beta.55
  rolldown-plugin-dts: ^0.19.2
  rxjs: ^7.8.2
  sass-embedded: ^1.97.1
  sax: ^1.4.3
  show-open-file-picker: ^0.4.0
  sql-highlight: ^6.1.0
  superjson: ^2.2.6
  survey-core: ^2.5.1
  survey-creator-core: ^2.5.1
  survey-creator-vue: ^2.5.1
  survey-vue3-ui: ^2.5.1
  three: ^0.182.0
  three-globe: ^2.45.0
  trpc-nuxt: ^2.0.1
  tsx: ^4.21.0
  type-fest: ^5.3.1
  typedoc: ^0.28.15
  typescript: ^5.9.3
  typescript-eslint: ^8.50.0
  unocss: ^66.5.10
  unplugin-auto-import: ^20.3.0
  v-viewer: ^3.0.22
  viewerjs: ^1.11.7
  vite: 8.0.0-beta.2
  vite-plugin-dts: ^4.5.4
  vite-plugin-mkcert: ^1.17.9
  vitest: ^4.0.16
  vue: ^3.5.26
  vue-codemirror: ^6.1.1
  vue-pdf-embed: ^2.1.3
  vue-router: ^4.6.4
  vue-tsc: ^3.2.1
  vue3-apexcharts: ^1.10.0
  vuetify: ^3.11.4
  vuetify-nuxt-module: ^0.19.1
  web-push: ^3.6.7
  worker-timers: ^8.0.27
  ws: ^8.18.3
  xmlbuilder2: ^4.0.3
  zod: ^4.2.1

catalogMode: strict

cleanupUnusedCatalogs: true

onlyBuiltDependencies:
  - "@parcel/watcher"
  - better-sqlite3
  - core-js
  - esbuild
  - unrs-resolver
  - vue-demi

overrides:
  pdfjs-dist: ^5.4.449
  vite: 8.0.0-beta.2

shellEmulator: true
