packages:
  - packages/*
catalog:
  "@azure/data-tables": ^13.3.0
  "@azure/storage-blob": ^12.27.0
  "@codemirror/lang-vue": ^0.1.3
  "@codemirror/language": ^6.11.0
  "@codemirror/language-data": ^6.5.1
  "@codemirror/state": ^6.5.2
  "@codemirror/theme-one-dark": ^6.1.2
  "@codemirror/view": ^6.36.4
  "@fullcalendar/core": ^6.1.15
  "@fullcalendar/daygrid": ^6.1.15
  "@fullcalendar/interaction": ^6.1.15
  "@fullcalendar/timegrid": ^6.1.15
  "@fullcalendar/vue3": ^6.1.15
  "@koumoul/vjsf": ^3.13.1
  "@lerna-lite/cli": ^4.0.0
  "@lerna-lite/publish": ^4.0.0
  "@lerna-lite/run": ^4.0.0
  "@mdi/font": ^7.4.47
  "@nuxt/eslint": ^1.2.0
  "@nuxt/fonts": ^0.11.0
  "@nuxt/scripts": ^0.11.5
  "@nuxt/test-utils": ^3.17.2
  "@nuxtjs/seo": ^3.0.1
  "@pinia/nuxt": ^0.10.1
  "@rollup/plugin-commonjs": ^28.0.3
  "@rollup/plugin-json": ^6.1.0
  "@rollup/plugin-node-resolve": ^16.0.1
  "@rollup/plugin-typescript": ^12.1.2
  "@tiptap/core": ^2.11.6
  "@tiptap/extension-character-count": ^2.11.6
  "@tiptap/extension-link": ^2.11.6
  "@tiptap/extension-mention": ^2.11.6
  "@tiptap/extension-placeholder": ^2.11.6
  "@tiptap/pm": ^2.11.6
  "@tiptap/starter-kit": ^2.11.6
  "@tiptap/suggestion": ^2.11.6
  "@tiptap/vue-3": ^2.11.6
  "@trpc/client": ^11.0.0
  "@trpc/server": ^11.0.0
  "@types/data-urls": ^3.0.4
  "@types/dedent": ^0.7.2
  "@types/deep-equal": ^1.0.4
  "@types/fs-extra": ^11.0.4
  "@types/howler": ^2.2.12
  "@types/js-beautify": ^1.14.3
  "@types/json-schema": ^7.0.15
  "@types/mjml-browser": ^4.15.0
  "@types/node": ^22.13.14
  "@types/omit-deep-lodash": ^1.1.3
  "@types/pluralize": ^0.0.33
  "@types/three": ^0.174.0
  "@types/ws": ^8.18.0
  "@types/xml2js": ^0.4.14
  "@unocss/eslint-config": ^66.0.0
  "@unocss/nuxt": ^66.0.0
  "@vite-pwa/nuxt": ^0.10.8
  "@vitejs/plugin-vue": ^5.2.3
  "@vitest/coverage-v8": ^3.0.9
  "@vitest/eslint-plugin": ^1.1.38
  "@vue-flow/background": ^1.3.2
  "@vue-flow/controls": ^1.1.2
  "@vue-flow/core": ^1.42.4
  "@vue-flow/minimap": ^1.5.2
  "@vue-flow/node-resizer": ^1.4.0
  "@vue/test-utils": ^2.4.6
  "@vuepic/vue-datepicker": ^11.0.2
  "@vueuse/core": ^13.0.0
  "@vueuse/integrations": ^13.0.0
  "@vueuse/nuxt": ^13.0.0
  # https://github.com/json-layout/json-layout/issues/5
  ajv: ^8.17.1
  # https://github.com/json-layout/json-layout/issues/5
  ajv-errors: ^3.0.0
  # https://github.com/json-layout/json-layout/issues/5
  ajv-formats: ^3.0.1
  # https://github.com/json-layout/json-layout/issues/5
  ajv-i18n: ^4.2.0
  apexcharts: ^4.5.0
  # @TODO: https://github.com/better-auth/better-auth/issues/1669
  better-auth: 1.1.21
  # @TODO: Remove when es decorators are released
  class-transformer: ^0.5.1
  codemirror: ^6.0.1
  cross-env: ^7.0.3
  ctix: ^2.7.0
  data-urls: ^5.0.0
  dayjs: ^1.11.13
  # https://github.com/json-layout/json-layout/issues/5
  debug: ^4.4.0
  dedent: ^1.5.3
  defu: ^6.1.4
  dotenv: ^16.4.7
  drizzle-kit: ^0.30.6
  drizzle-orm: ^0.41.0
  drizzle-zod: ^0.7.1
  emoji-mart-vue-fast: ^15.0.4
  eslint: ^9.23.0
  eslint-config-prettier: ^10.1.1
  eslint-plugin-perfectionist: ^4.10.1
  eslint-plugin-pinia: ^0.4.1
  eslint-plugin-prettier: ^5.2.5
  eventemitter3: ^5.0.1
  fast-deep-equal: ^3.1.3
  fs-extra: ^11.3.0
  fuse.js: ^7.1.0
  grapesjs: ^0.22.6
  grapesjs-blocks-basic: ^1.0.2
  grapesjs-component-countdown: ^1.0.2
  grapesjs-custom-code: ^1.0.2
  grapesjs-mjml: ^1.0.6
  grapesjs-parser-postcss: ^1.0.3
  grapesjs-plugin-export: ^1.0.12
  grapesjs-plugin-forms: ^2.0.6
  grapesjs-preset-webpage: ^1.0.3
  grapesjs-style-bg: ^2.0.2
  grapesjs-tabs: ^1.0.6
  grapesjs-tooltip: ^0.1.8
  grapesjs-touch: ^0.1.1
  grapesjs-tui-image-editor: ^1.0.2
  grapesjs-typed: ^2.0.1
  grid-engine: ^2.47.0
  grid-layout-plus: ^1.0.6
  gsap: ^3.12.7
  h3: ^1.15.1
  happy-dom: ^17.4.4
  howler: ^2.2.4
  is-mobile: ^5.0.0
  js-beautify: ^1.15.4
  marked: ^15.0.7
  mjml-browser: ^4.15.3
  node-emoji: ^2.2.0
  node-html-parser: ^7.0.1
  nuxt: ^3.16.1
  nuxt-security: ^2.2.0
  obscenity: ^0.4.3
  omit-deep-lodash: ^1.1.7
  pathe: ^2.0.3
  phaser: ^3.88.2
  phaser3-rex-plugins: ^1.80.14
  pinia: ^3.0.1
  pluralize: ^8.0.0
  postgres: ^3.4.5
  prettier: ^3.5.3
  rate-limiter-flexible: ^6.2.1
  rollup: ^4.37.0
  rollup-plugin-dts: ^6.2.1
  rxjs: ^7.8.2
  sass-embedded: ^1.86.0
  sql-highlight: ^6.0.0
  superjson: ^2.2.2
  survey-core: ^2.0.2
  survey-creator-core: ^2.0.2
  survey-creator-vue: ^2.0.2
  survey-vue3-ui: ^2.0.2
  three: ^0.174.0
  three-globe: ^2.42.3
  tippy.js: ^6.3.7
  trpc-nuxt: ^1.0.4
  tsx: ^4.19.3
  type-fest: ^4.38.0
  typedoc: ^0.28.1
  typescript: ^5.8.2
  typescript-eslint: ^8.28.0
  unocss: ^66.0.0
  unplugin-auto-import: ^19.1.2
  vite: ^6.2.3
  vite-plugin-dts: ^4.5.3
  vite-plugin-mkcert: ^1.17.8
  vite-plugin-node-polyfills: ^0.23.0
  vite-tsconfig-paths: ^5.1.4
  vitest: ^3.0.9
  vue: ^3.5.13
  vue-codemirror: ^6.1.1
  vue-router: ^4.5.0
  vue-tsc: ^2.2.8
  vue-waypoint: ^4.3.0
  vue3-apexcharts: ^1.8.0
  vuetify: ^3.7.19
  vuetify-nuxt-module: ^0.18.4
  vuetify-sonner: ^0.3.21
  worker-timers: ^8.0.20
  ws: ^8.18.1
  xml2js: ^0.6.2
  zod: ^3.24.2
  zod-to-json-schema: ^3.24.5
onlyBuiltDependencies:
  - "@parcel/watcher"
  - core-js
  - esbuild
  - vue-demi
