export const RoutePath = {
  About: "/about",
  Anime: "/anime",
  Calendar: "/calendar",
  Clicker: "/clicker",
  Dashboard: "/dashboard",
  DashboardEditor: "/dashboard/editor",
  Docs: "/docs",
  Dungeons: "/dungeons",
  EmailEditor: "/email-editor",
  FlowchartEditor: "/flowchart-editor",
  Github: "https://github.com/Esposter/Esposter",
  Index: "/",
  Login: "/login",
  Messages: (id: string) => `/messages/${id}`,
  MessagesGg: (inviteCode: string) => `/messages/gg/${inviteCode}`,
  MessagesIndex: "/messages",
  Post: (id: string) => `/post/${id}`,
  PostCreate: "/post/create",
  PostUpdate: (id: string) => `/post/update/${id}`,
  PrivacyPolicy: "https://www.termsfeed.com/live/367522f3-27be-4faa-a7bd-dda7b419a8fc",
  Survey: (id: string) => `/surveyer/${id}`,
  Surveyer: "/surveyer",
  TableEditor: "/table-editor",
  TermsAndConditions: "https://www.termsfeed.com/live/7202726c-ae87-41cd-af54-9bde6ca4477a",
  UserSettings: "/user/settings",
  WebpageEditor: "/webpage-editor",
} as const;
export type RoutePath = typeof RoutePath;
