import type { CameraConfigField } from "#src/models/genshinAssets/camera/CameraConfigField";

// The game's play camera, a ScriptableObject named in the asset index: a config for each camera module, then one global
// Config, exported raw as one file of this name
export const CAMERA_PROFILE_NAME = "CameraProfile";
// The global config's words in order, each named by the il2cpp dummy scripts of a 2022 build
// (github.com/fengjixuchui/WorldReverse, `MoleMole/PipelineCameraGlobalConfig.cs`), whose order the current build keeps
// With twelve fields added: the paired values fall on their pairs and every flag on a 0 or a 1. The first five words hold
// The default elevations and the anchor's distance in order with one added field, whose place their values do not tell,
// So none of the five is named
export const CAMERA_GLOBAL_CONFIG_FIELDS: readonly CameraConfigField[] = [
  { name: "" },
  { name: "" },
  { name: "" },
  { name: "" },
  { name: "" },
  { name: "MIN_ELEVATION_ANGLE" },
  { name: "MAX_ELEVATION_ANGLE" },
  { name: "PARA_MIN_ELEVATION_ANGLE" },
  { name: "PARA_MAX_ELEVATION_ANGLE" },
  { name: "MIN_CAMERA_ZOOM_RADIUS" },
  { name: "DELTA_TO_ANCHOR_ANGULAR_POLAR_RATIO" },
  { name: "DELTA_TO_ANCHOR_ANGULAR_ELEVATION_RATIO" },
  { name: "DELTA_TO_ZOOM_RATIO" },
  { name: "HIT_WALL_OR_GROUND_TOLERANCE" },
  { name: "K_AVATAR_HEIGHT_TO_DEFAULT_LOCAL_RATIO" },
  { name: "B_AVATAR_HEIGHT_TO_DEFAULT_LOCAL_RATIO" },
  { name: "K_AVATAR_HEIGHT_TO_DEFAULT_LOCAL_RATIO_PARA" },
  { name: "B_AVATAR_HEIGHT_TO_DEFAULT_LOCAL_RATIO_PARA" },
  { name: "K_AVATAR_HEIGHT_TO_DEFAULT_LOCAL_RATIO_FLY" },
  { name: "B_AVATAR_HEIGHT_TO_DEFAULT_LOCAL_RATIO_FLY" },
  { name: "MAX_RADIUS_MOVING" },
  { name: "MAX_RADIUS_CLIMBING" },
  { name: "MAX_RADIUS_FLYING" },
  { name: "MAX_RADIUS_COMBAT" },
  { name: "" },
  { name: "" },
  { name: "" },
  { name: "" },
  { name: "" },
  { name: "" },
  { name: "" },
  { name: "" },
  { name: "" },
  { isFlag: true, name: "SETTING_ALWAYS_SLOPECHECK" },
  { isFlag: true, name: "SETTING_ALWAYS_COMBAT_LOCK" },
  { isFlag: true, name: "SETTING_ALWAYS_BOSSADJUST" },
  { name: "SETTING_RADIUS_ADJUST_MIN_PC" },
  { name: "SETTING_RADIUS_ADJUST_MIN_PS4" },
  { name: "SETTING_RADIUS_ADJUST_MIN_MOBILE" },
  { name: "SETTING_RADIUS_ADJUST_MAX_PC" },
  { name: "SETTING_RADIUS_ADJUST_MAX_PS4" },
  { name: "SETTING_RADIUS_ADJUST_MAX_MOBILE" },
  { name: "" },
  { name: "" },
  { name: "ADD_RADIUS_DURING_MAX_ELEVATION" },
  { name: "DEFAULT_CAMERA_LOCATE_RATIO" },
  { name: "ENEMY_DETECT_RADIUS_FROM_AVATAR" },
  { name: "ENEMY_HEIGHT_DETECT_RADIUS_FROM_AVATAR" },
  { name: "HEIGHT_WARNING_RADIUS_MAX_RATIO" },
  { name: "DEFAULT_CAMERA_BIG_RATIO" },
  { name: "MAX_CAMERA_BIG_RATIO" },
  { isFlag: true, name: "ENABLE_SLOP_PC" },
  { isFlag: true, name: "ENABLE_SLOP_PS4" },
  { isFlag: true, name: "ENABLE_SLOP_SWITCH" },
  { isFlag: true, name: "ENABLE_SLOP_MOBILE" },
  { isFlag: true, name: "ENABLE_SLOP_EDITOR" },
  { isFlag: true, name: "ENABLE_CAMERA_RECENTERING_PC" },
  { isFlag: true, name: "ENABLE_CAMERA_RECENTERING_PS4" },
  { isFlag: true, name: "ENABLE_CAMERA_RECENTERING_SWITCH" },
  { isFlag: true, name: "ENABLE_CAMERA_RECENTERING_MOBILE" },
  { isFlag: true, name: "ENABLE_CAMERA_RECENTERING_EDITOR" },
  { name: "CAMERA_RECENTERING_KEEP_ROTATION_TRIGGER_TIME" },
  { name: "CAMERA_RECENTERING_TRIGGER_TIME" },
  { name: "CAMERA_RECENTERING_TRIGGER_INPUT_ANGLE" },
  { name: "FOCUS_OFFSET_ANGLE" },
  { name: "FOCUS_START_OFFSET_ANGLE" },
  { name: "NEAR_PLANE_WIDTH_CHECK_RATIO" },
  { name: "COMBAT_PULL_DISTANCE" },
  { name: "COMBAT_PULL_INTERVAL" },
  { name: "COMBAT_PULL_EXIT_INTERVAL" },
];
