import type { SpinnerContent } from "#src/models/SpinnerContent";

// The base the spinner shows for every character: the verbs ahead of the character's own, the tips only for a
// Character whose card has none. A tip here is nobody's line, shown under the tool's own "Tip" prefix rather than
// A character's name
export const BASE_SPINNER_CONTENT: SpinnerContent = {
  tips: [
    "Glide when the cliff is tall and climb when it is not. The stamina is the same either way.",
    "A Statue of The Seven mends what a long road did. Stand near one before the next fight.",
    "Cook before the fight, never during it.",
    "Every commission ends the same way. Report back, collect, rest.",
    "Teleport where the road is known. Walk where it is not, because that is how waypoints are found.",
    "Wish sparingly. Pity is patience, not a plan.",
    "A domain is cleared one room at a time, and so is a task.",
    "Save the burst for the shield, not the slime.",
    "The map remembers where you have been so you do not have to.",
    "Rain slows the road and sharpens Hydro. Wait it out, or use it.",
    "Paimon would say it is time to eat. Paimon is usually right.",
    "Read the tablet before pressing the switch. The puzzle is always explained once.",
    "A chest under a rock is still a chest.",
    "Commissions reset at dawn. So does your patience, if you let it.",
    "Sprint on the flat and walk the slope, and the stamina lasts the whole hill.",
  ],
  verbs: [
    "Adventuring",
    "Alchemizing",
    "Ascending",
    "Brewing",
    "Charting",
    "Climbing",
    "Commissioning",
    "Cooking",
    "Crafting",
    "Dashing",
    "Delving",
    "Diving",
    "Enhancing",
    "Exploring",
    "Farming",
    "Fishing",
    "Foraging",
    "Forging",
    "Gathering",
    "Gliding",
    "Harvesting",
    "Hunting",
    "Leveling",
    "Mapping",
    "Mining",
    "Questing",
    "Refining",
    "Resting",
    "Roasting",
    "Sailing",
    "Scouting",
    "Sprinting",
    "Surveying",
    "Swimming",
    "Teleporting",
    "Tracking",
    "Trekking",
    "Wandering",
    "Wayfinding",
    "Wishing",
  ],
};
