import type { CraftingRecipe } from "#src/models/crafting/CraftingRecipe";
import type { Inventory } from "#src/models/inventory/Inventory";
import type { ItemDefinition } from "#src/models/inventory/ItemDefinition";

import { CraftingRecipeKind } from "#src/models/crafting/CraftingRecipeKind";
import { Currency } from "#src/models/inventory/Currency";
import { computeCraftableCount } from "#src/services/crafting/computeCraftableCount";
import { ORIGINAL_RESIN_ITEM_ID } from "#src/services/crafting/constants";
import { EMPTY_WALLET } from "#src/services/inventory/constants";
import { ORIGINAL_RESIN_REGEN_MINUTES } from "#src/services/originalResin/constants";
import { ItemCategory } from "genshin-interface";
import { describe, expect, test } from "vitest";

const createDefinition = (id: number): ItemDefinition => ({
  category: ItemCategory.Material,
  id,
  name: "",
  rank: 0,
  rarity: 0,
  stackLimit: 99,
});

describe(computeCraftableCount, () => {
  const EPOCH = Temporal.Instant.fromEpochMilliseconds(0);
  const MATERIAL_ID = 112_002;
  const CRYSTAL_CORE_ID = 100_085;
  const materialDefinition = createDefinition(MATERIAL_ID);
  const crystalCoreDefinition = createDefinition(CRYSTAL_CORE_ID);
  const recipe: CraftingRecipe = {
    id: 11_002,
    kind: CraftingRecipeKind.Tier,
    materials: [
      { count: 2, id: MATERIAL_ID },
      { count: 1, id: CRYSTAL_CORE_ID },
    ],
    mora: 0,
    playerLevel: 1,
    resultCount: 1,
    resultItemId: 112_004,
    unlockItemIds: [],
  };

  test("should take the least of what each material allows", () => {
    expect.hasAssertions();

    const inventory: Inventory = {
      items: [
        { definition: materialDefinition, id: 0, quantity: 5 },
        { definition: crystalCoreDefinition, id: 1, quantity: 1 },
      ],
      nextId: 2,
    };

    expect(computeCraftableCount(recipe, { inventory, wallet: EMPTY_WALLET }, EPOCH)).toBe(1);
  });

  test("should pay Original Resin from the wallet as it has regenerated by now", () => {
    expect.hasAssertions();

    const resinRecipe: CraftingRecipe = {
      ...recipe,
      materials: [
        { count: 60, id: ORIGINAL_RESIN_ITEM_ID },
        { count: 1, id: CRYSTAL_CORE_ID },
      ],
      mora: 100,
    };
    const inventory: Inventory = { items: [{ definition: crystalCoreDefinition, id: 0, quantity: 9 }], nextId: 1 };
    const wallet = { ...EMPTY_WALLET, [Currency.Mora]: 250, [Currency.OriginalResin]: 0 };
    const now = EPOCH.add({ minutes: ORIGINAL_RESIN_REGEN_MINUTES * 120 });

    expect(computeCraftableCount(resinRecipe, { inventory, wallet }, now)).toBe(2);
  });
});
