export enum DatabaseEntityType {
  Achievement = "Achievement",
  AppUser = "AppUser",
  Ban = "Ban",
  Block = "Block",
  Friend = "Friend",
  FriendRequest = "FriendRequest",
  Invite = "Invite",
  Like = "Like",
  Post = "Post",
  PushSubscription = "PushSubscription",
  Room = "Room",
  RoomCategory = "RoomCategory",
  RoomFilter = "RoomFilter",
  RoomRole = "RoomRole",
  SearchHistory = "SearchHistory",
  Survey = "Survey",
  User = "User",
  UserAchievement = "UserAchievement",
  UserStatus = "UserStatus",
  UserToRoom = "UserToRoom",
  UserToRoomRole = "UserToRoomRole",
  Verification = "Verification",
  Webhook = "Webhook",
}
