import type { BaseLandmark } from "#src/models/world/BaseLandmark";
import type { RegionBuilding } from "#src/models/world/RegionBuilding";

import { baseLandmarkSchema } from "#src/models/world/BaseLandmark";
import { LandmarkKind } from "#src/models/world/LandmarkKind";
import { regionBuildingSchema } from "#src/models/world/RegionBuilding";
import { z } from "zod";

// A building, such as a capital's first hall, generated by its region's kit from that kit's options
export interface BuildingLandmark extends BaseLandmark {
  building: RegionBuilding;
  kind: LandmarkKind.Building;
}

export const buildingLandmarkSchema = baseLandmarkSchema.safeExtend({
  building: regionBuildingSchema,
  kind: z.literal(LandmarkKind.Building),
}) satisfies z.ZodType<BuildingLandmark>;
