// The kit a building landmark is generated by: each region's own, named by its region, the one its towns are built from
export enum BuildingKit {
  Fontaine = "Fontaine",
  Inazuma = "Inazuma",
  Liyue = "Liyue",
  Mondstadt = "Mondstadt",
  Natlan = "Natlan",
  NodKrai = "NodKrai",
  Snezhnaya = "Snezhnaya",
  Sumeru = "Sumeru",
}
