import ApplicationTags from "@/constants/ApplicationTags";
import AzureGlobalLocation from "@/constants/AzureGlobalLocation";
import { devAgEsposter002 } from "@/resources/Microsoft.Insights/actionGroups/devAgEsposter002";
import { devAppiEsposterAe001 } from "@/resources/Microsoft.Insights/components/devAppiEsposterAe001";
import { devRgEsposterAe001 } from "@/resources/Microsoft.Resources/resourceGroups/devRgEsposterAe001";
import { getSmartDetectorResourceId } from "@/services/getSmartDetectorResourceId";
import * as azure_native from "@pulumi/azure-native";

const alertRuleName = "Trace Severity Degradation - dev-appi-esposter-ae-001";

export const devAppiEsposterAe001TraceSeverityDegradation: azure_native.alertsmanagement.SmartDetectorAlertRule =
  new azure_native.alertsmanagement.SmartDetectorAlertRule(
    alertRuleName,
    {
      actionGroups: {
        groupIds: [
          getSmartDetectorResourceId(
            devRgEsposterAe001.name,
            "microsoft.insights",
            "actiongroups",
            devAgEsposter002.name,
          ),
        ],
      },
      alertRuleName,
      description:
        "Trace Severity Degradation notifies you of an unusual increase in the severity of the traces generated by your app.",
      detector: {
        id: "TraceSeverityDetector",
      },
      frequency: "P1D",
      location: AzureGlobalLocation,
      resourceGroupName: devRgEsposterAe001.name,
      scope: [
        getSmartDetectorResourceId(
          devRgEsposterAe001.name,
          "microsoft.insights",
          "components",
          devAppiEsposterAe001.name,
        ),
      ],
      severity: azure_native.alertsmanagement.Severity.Sev3,
      state: azure_native.alertsmanagement.AlertRuleState.Enabled,
      tags: {
        ...ApplicationTags,
      },
    },
    {
      parent: devRgEsposterAe001,
      protect: true,
    },
  );
