import ApplicationTags from "@/constants/ApplicationTags";
import AzureGlobalLocation from "@/constants/AzureGlobalLocation";
import { devAgEsposterAuea002 } from "@/resources/Microsoft.Insights/actionGroups/devAgEsposterAuea002";
import { dShpAppiEsposterAuea001 } from "@/resources/Microsoft.Insights/components/dShpAppiEsposterAuea001";
import { dShpRgEsposterAuea001 } from "@/resources/Microsoft.Resources/resourceGroups/dShpRgEsposterAuea001";
import { getSmartDetectorResourceId } from "@/services/getSmartDetectorResourceId";
import * as azure_native from "@pulumi/azure-native";

export const dShpAppiEsposterAuea001TraceSeverityDegradation: azure_native.alertsmanagement.SmartDetectorAlertRule =
  new azure_native.alertsmanagement.SmartDetectorAlertRule(
    "Trace Severity Degradation - d-shp-appi-esposter-auea-001",
    {
      actionGroups: {
        groupIds: [
          getSmartDetectorResourceId(
            dShpRgEsposterAuea001.name,
            "microsoft.insights",
            "actiongroups",
            devAgEsposterAuea002.name,
          ),
        ],
      },
      alertRuleName: "Trace Severity Degradation - d-shp-appi-esposter-auea-001",
      description:
        "Trace Severity Degradation notifies you of an unusual increase in the severity of the traces generated by your app.",
      detector: {
        id: "TraceSeverityDetector",
      },
      frequency: "P1D",
      location: AzureGlobalLocation,
      resourceGroupName: dShpRgEsposterAuea001.name,
      scope: [
        getSmartDetectorResourceId(
          dShpRgEsposterAuea001.name,
          "microsoft.insights",
          "components",
          dShpAppiEsposterAuea001.name,
        ),
      ],
      severity: azure_native.alertsmanagement.Severity.Sev3,
      state: azure_native.alertsmanagement.AlertRuleState.Enabled,
      tags: {
        ...ApplicationTags,
      },
    },
    {
      protect: true,
    },
  );
