import ApplicationTags from "@/constants/ApplicationTags";
import AzureGlobalLocation from "@/constants/AzureGlobalLocation";
import { prodAgEsposterAuea002 } from "@/resources/Microsoft.Insights/actionGroups/prodAgEsposterAuea002";
import { pShpAppiEsposterAuea001 } from "@/resources/Microsoft.Insights/components/pShpAppiEsposterAuea001";
import { pShpRgEsposterAuea001 } from "@/resources/Microsoft.Resources/resourceGroups/pShpRgEsposterAuea001";
import { getSmartDetectorResourceId } from "@/services/getSmartDetectorResourceId";
import * as azure_native from "@pulumi/azure-native";

export const pShpAppiEsposterAuea001TraceSeverityDegradation: azure_native.alertsmanagement.SmartDetectorAlertRule =
  new azure_native.alertsmanagement.SmartDetectorAlertRule(
    "Trace Severity Degradation - p-shp-appi-esposter-auea-001",
    {
      actionGroups: {
        groupIds: [
          getSmartDetectorResourceId(
            pShpRgEsposterAuea001.name,
            "microsoft.insights",
            "actiongroups",
            prodAgEsposterAuea002.name,
          ),
        ],
      },
      alertRuleName: "Trace Severity Degradation - p-shp-appi-esposter-auea-001",
      description:
        "Trace Severity Degradation notifies you of an unusual increase in the severity of the traces generated by your app.",
      detector: {
        id: "TraceSeverityDetector",
      },
      frequency: "P1D",
      location: AzureGlobalLocation,
      resourceGroupName: pShpRgEsposterAuea001.name,
      scope: [
        getSmartDetectorResourceId(
          pShpRgEsposterAuea001.name,
          "microsoft.insights",
          "components",
          pShpAppiEsposterAuea001.name,
        ),
      ],
      severity: azure_native.alertsmanagement.Severity.Sev3,
      state: azure_native.alertsmanagement.AlertRuleState.Enabled,
      tags: {
        ...ApplicationTags,
      },
    },
    {
      protect: true,
    },
  );
