export enum CommandType {
  CreateColumn = "CreateColumn",
  CreateComputedColumn = "CreateComputedColumn",
  CreateRow = "CreateRow",
  CreateRows = "CreateRows",
  DeleteColumn = "DeleteColumn",
  DeleteColumns = "DeleteColumns",
  DeleteRow = "DeleteRow",
  DeleteRows = "DeleteRows",
  FindReplace = "FindReplace",
  MoveColumn = "MoveColumn",
  MoveRow = "MoveRow",
  NullStrategy = "NullStrategy",
  StringTransformation = "StringTransformation",
  ToggleColumnVisibility = "ToggleColumnVisibility",
  UpdateColumn = "UpdateColumn",
  UpdateRow = "UpdateRow",
}
