import type { Localization } from "#src/models/Localization";

// The spinner's gerunds read as the "…中" a Chinese interface puts on a running task, so a turn reads the way the
// Game's own interface does. Everything the data package or the game carries — the names, titles, elements,
// Regions, descriptions and every character's own voice lines — is absent here and asked of them
const chineseSimplified: Localization = {
  characters: {
    Aether: { greeting: "嗨。派蒙说有活要干。", verbs: ["旅行中", "搜寻中", "滑翔中", "倾听中"] },
    Aino: { greeting: "哦，新项目？把扳手递给我。", verbs: ["捣鼓中", "拧螺丝中", "发明中", "吃零食中"] },
    Albedo: { greeting: "有意思。工作时我可以做笔记吗？", verbs: ["写生中", "炼成中", "调查中", "研究中"] },
    Alhaitham: { greeting: "把请求说清楚，我自会处理。", verbs: ["阅读中", "驳回中", "归档中", "推理中"] },
    Aloy: { greeting: "新的土地，同一把弓。要做什么？", verbs: ["狩猎中", "侦察中", "接管中", "追踪中"] },
    Alyosha: { greeting: "足迹还新鲜。走吧。", verbs: ["狩猎中", "追踪中", "狙击中", "记账中"] },
    Amber: { greeting: "侦察骑士报到！任务是什么？", verbs: ["滑翔中", "奔跑中", "侦察中", "烤点心中"] },
    "Arataki Itto": { greeting: "独一无二的鬼来了！冲啊！", verbs: ["打架中", "斗虫中", "吹牛中", "获胜中"] },
    Arlecchino: { greeting: "让这份合作保持愉快吧。开始。", verbs: ["监督中", "裁决中", "派遣中", "观察中"] },
    Baizhu: { greeting: "坐。说说哪里不舒服，从什么时候开始。", verbs: ["问诊中", "开方中", "分拣中", "休养中"] },
    Barbara: { greeting: "当当！加油打气就交给我吧！", verbs: ["治疗中", "唱歌中", "应援中", "练习中"] },
    Beidou: { greeting: "欢迎登船。后背交给我。", verbs: ["航行中", "切磋中", "喝酒中", "指挥中"] },
    Bennett: { greeting: "队里还能再加一个人吗？拜托？", verbs: ["冒险中", "寻宝中", "摔跤中", "烧烤中"] },
    Candace: { greeting: "在这里休息吧。我来守夜。", verbs: ["守卫中", "巡逻中", "护盾中", "警戒中"] },
    Charlotte: { greeting: "有空接受个独家采访吗？", verbs: ["报道中", "拍照中", "采访中", "洗照片中"] },
    Chasca: { greeting: "有纠纷要调停吗？开个价吧。", verbs: ["翱翔中", "调停中", "盘旋中", "装弹中"] },
    Chevreuse: { greeting: "客套就免了。哪个案子？", verbs: ["调查中", "瞄准中", "吃零食中", "巡逻中"] },
    Chiori: { greeting: "是订制还是闲聊？只有一样免费。", verbs: ["裁缝中", "裁剪中", "试衣中", "午睡中"] },
    Chongyun: { greeting: "荣幸之至。我们冷静地开始吧？", verbs: ["驱邪中", "降温中", "念咒中", "调查中"] },
    Citlali: { greeting: "烟说你会来。行吧。什么事？", verbs: ["观星中", "占卜中", "阅读中", "喝酒中"] },
    Clorinde: { greeting: "说出你的纠纷。细节免了。", verbs: ["决斗中", "裁决中", "巡逻中", "狩猎中"] },
    Collei: { greeting: "见习生报到！我练习过了。做对了吗？", verbs: ["巡逻中", "缝纫中", "滑翔中", "汇报中"] },
    Columbina: { greeting: "月亮升起来了。一起在月下走走吗？", verbs: ["赏月中", "唱歌中", "祝福中", "散步中"] },
    Cyno: { greeting: "审判开始。或者来一局卡牌，你选。", verbs: ["审判中", "抽卡中", "权衡中", "讲冷笑话中"] },
    Dahlia: { greeting: "风把你带来了。坐吧，放轻松。", verbs: ["倾听中", "漫游中", "打听八卦中", "祝福中"] },
    Dehya: { greeting: "佣兵来了。委托、打架，还是护送？", verbs: ["守卫中", "护送中", "打架中", "重整中"] },
    Diluc: { greeting: "省去寒暄。要做什么？", verbs: ["斟酒中", "准备中", "出击中", "经营中"] },
    Diona: { greeting: "猫尾酒馆打烊了。……好吧，进来。", verbs: ["调酒中", "扑击中", "狩猎中", "哈气中"] },
    Dori: { greeting: "啊，客人！第一单超值哦。", verbs: ["砍价中", "算账中", "交易中", "打折中"] },
    Durin: { greeting: "你好！这也是故事的一部分吗？", verbs: ["探索中", "玩耍中", "散步中", "学习中"] },
    Emilie: { greeting: "和香水有关？如果不是，换个安静的地方。", verbs: ["蒸馏中", "装瓶中", "修剪中", "调香中"] },
    Escoffier: { greeting: "系好围裙。今天摆什么盘？", verbs: ["摆盘中", "收汁中", "调温中", "磨刀中"] },
    Eula: { greeting: "浪花骑士向你问好。没错，就是那个劳伦斯。", verbs: ["侦察中", "谴责中", "冰冻中", "立誓中"] },
    Faruzan: { greeting: "说话前先看看我的资历，小家伙。", verbs: ["破译中", "解谜中", "讲课中", "写经费申请中"] },
    Fischl: { greeting: "皇女降临！奥兹，翻译一下：你好。", verbs: ["颁布诏令中", "预言中", "降临中", "翻译中"] },
    Flins: { greeting: "欢迎来到岛上。小心那些坟墓。", verbs: ["守灯塔中", "收集中", "倾听中", "照料中"] },
    Freminet: { greeting: "嗨。不用握手。下面有什么？", verbs: ["潜水中", "打捞中", "拆解中", "勘测中"] },
    Furina: { greeting: "惊呆了？可以理解。明星驾到。", verbs: ["演出中", "排练中", "摆姿势中", "主持中"] },
    Gaming: { greeting: "嘿老板！坐着，重活我来。", verbs: ["护送中", "打包中", "打鼓中", "吃零食中"] },
    Ganyu: { greeting: "协议拟好了……啊，忘记签字了。", verbs: ["归档中", "起草中", "吃草中", "加班中"] },
    Gorou: { greeting: "五郎大将，准备完毕！并肩迈向胜利！", verbs: ["操练中", "集结中", "攀登中", "侦察中"] },
    "Hu Tao": { greeting: "哟！找堂主吗？气色这么好，可惜了。", verbs: ["推销中", "作诗中", "恶作剧中", "开溜中"] },
    Iansan: { greeting: "热身结束。今天练哪一组？", verbs: ["举铁中", "指导中", "算热量中", "示范中"] },
    Ifa: { greeting: "哦，嗨。不急。有什么烦心事？", verbs: ["诊断中", "弹琴中", "吃零食中", "观察自然中"] },
    Illuga: { greeting: "噩梦黄鹂。快，汇报。", verbs: ["调查中", "巡逻中", "带队中", "做饭中"] },
    Ineffa: { greeting: "系统就绪！轰轰，出发！", verbs: ["清扫中", "分拣中", "更新中", "充电中"] },
    Jahoda: { greeting: "博物馆的超级员工，为您效劳！", verbs: ["跑腿中", "缝纫中", "探索中", "讲价中"] },
    Jean: { greeting: "蒲公英骑士，在你身边。", verbs: ["批阅中", "行军中", "审核中", "拉伸中"] },
    Kachina: { greeting: "你好！我还不够强，但我会努力的！", verbs: ["挖掘中", "堆叠中", "收藏中", "钻探中"] },
    "Kaedehara Kazuha": { greeting: "风带来了一句诗，还有你。幸会。", verbs: ["漫游中", "漂泊中", "吟诗中", "倾听中"] },
    Kaeya: { greeting: "这应该比骑士的工作有趣。", verbs: ["谋划中", "品酒中", "冰冻中", "调侃中"] },
    "Kamisato Ayaka": { greeting: "神里绫华，在此。很高兴见到你。", verbs: ["舞蹈中", "作曲中", "练习中", "主持中"] },
    "Kamisato Ayato": { greeting: "终于见面了；我的日程向你致歉。", verbs: ["谋划中", "委派中", "钓鱼中", "品尝中"] },
    Kaveh: { greeting: "品味相近？那我们一定合得来。", verbs: ["设计中", "画图中", "打磨中", "超支中"] },
    Keqing: { greeting: "一个变革的时代。来见证吧。", verbs: ["改革中", "赶时间中", "购物中", "委派中"] },
    Kinich: { greeting: "说明情况。报个价。", verbs: ["狩猎中", "估价中", "钩索中", "垂降中"] },
    Kirara: { greeting: "快递来啦！没有太远的地方，喵。", verbs: ["送货中", "飞奔中", "扑击中", "规划路线中"] },
    Klee: { greeting: "火花骑士可莉！……后面的忘了。", verbs: ["爆炸中", "炸鱼中", "蹦跳中", "反省中"] },
    "Kujou Sara": { greeting: "九条裟罗。稻妻已在守护之下。请讲。", verbs: ["操练中", "瞄准中", "守卫中", "晋升中"] },
    "Kuki Shinobu": { greeting: "荒泷派，副手接听。对，所有人。", verbs: ["修理中", "学习中", "考证中", "管束中"] },
    "Lan Yan": { greeting: "篮子、花瓶，还是陪伴？都有。", verbs: ["编织中", "采集中", "拼接中", "采花中"] },
    Lauma: { greeting: "林苑向你问候，我也一样。", verbs: ["祝福中", "倾听中", "漫游中", "休息中"] },
    Layla: { greeting: "嗯？抱歉，什么？哦。嗨。", verbs: ["梦游中", "绘星图中", "打哈欠中", "观星中"] },
    Linnea: { greeting: "奇观占卜师，为你参谋。你发现了什么？", verbs: ["编目中", "写生中", "观察中", "参谋中"] },
    Lisa: { greeting: "你好呀小可爱，来帮丽莎的忙吗？", verbs: ["泡茶中", "翻书中", "慵懒中", "放电中"] },
    Lohen: { greeting: "副队长。按规矩办会更慢。", verbs: ["瞄准中", "即兴中", "恶作剧中", "巡逻中"] },
    Lumine: { greeting: "你好。派蒙饿了，我们快点吧。", verbs: ["旅行中", "搜寻中", "滑翔中", "倾听中"] },
    Lynette: { greeting: "你好。有问题请找林尼。", verbs: ["协助中", "休息中", "泡茶中", "待命中"] },
    Lyney: { greeting: "不是幻术，就是我！今天心情如何？", verbs: ["表演中", "变魔术中", "消失中", "炫目中"] },
    Manekin: { greeting: "……！准备探索。", verbs: ["探索中", "捣鼓中", "解封中", "指引中"] },
    Manekina: { greeting: "……！先解哪个谜？", verbs: ["探索中", "捣鼓中", "解封中", "欣喜中"] },
    Mavuika: { greeting: "火焰点燃了。出发吧。", verbs: ["点燃中", "驾驶中", "集结中", "苦思中"] },
    Mika: { greeting: "测绘员报到。能帮上忙是我的荣幸。", verbs: ["测绘中", "制图中", "侦察中", "露营中"] },
    Mona: { greeting: "先把全名记住，再来提问。", verbs: ["占星中", "观星中", "做预算中", "节俭中"] },
    Mualani: { greeting: "向导来啦！需要什么就举手！", verbs: ["冲浪中", "追浪中", "戏水中", "导览中"] },
    Nahida: { greeting: "我已经看了你一会儿了。终于，你好。", verbs: ["做梦中", "好奇中", "提问中", "成长中"] },
    Navia: { greeting: "会长、老板，以及之间的一切。嗨！", verbs: ["主持中", "烘焙中", "旅行中", "指挥中"] },
    Nefer: { greeting: "博物馆开门了。在找什么隐藏之物吗？", verbs: ["策展中", "推理中", "观察中", "补水中"] },
    Neuvillette: { greeting: "你好。称呼姓氏即可。", verbs: ["审判中", "品鉴中", "评议中", "降雨中"] },
    Nicole: { greeting: "……你好。刚才那是吵闹的部分。", verbs: ["倾听中", "打手语中", "观察中"] },
    Nilou: { greeting: "舞蹈马上开始。留下来看吗？", verbs: ["跳舞中", "排练中", "旋转中", "绽放中"] },
    Ningguang: { greeting: "想做买卖？谈谈条件吧。", verbs: ["投资中", "谈判中", "主持中", "收藏中"] },
    Noelle: { greeting: "骑士团的女仆，今天也为您服务。", verbs: ["打扫中", "服务中", "训练中", "采购中"] },
    Odette: { greeting: "帷幕拉开了。我们开始吧？", verbs: ["排练中", "旋转足尖中", "签名中", "节食中"] },
    Ororon: { greeting: "哦，嗨。要根蔬菜吗？没什么理由。", verbs: ["种菜中", "播种中", "滑翔中", "观察蚜虫中"] },
    Prune: { greeting: "猎巫人普吕讷！见过女巫吗？有没有？", verbs: ["狩猎中", "批注中", "宣告中", "怒视中"] },
    Qiqi: { greeting: "七七。僵尸。……后面的忘了。", verbs: ["采药中", "遗忘中", "降温中", "数数中"] },
    "Raiden Shogun": { greeting: "不必问候。你来做向导。", verbs: ["颁令中", "拔刀中", "冥想中", "裁决中"] },
    Razor: { greeting: "你，好闻。现在，狩猎。", verbs: ["狩猎中", "奔跑中", "嗅闻中", "守护中"] },
    Rosaria: {
      greeting: "你处理不了的麻烦？那就是我。祈祷，去别处。",
      verbs: ["巡逻中", "喝酒中", "翘班中", "工作中"],
    },
    Sandrone: { greeting: "坐。茶已经量好了，你也会被量好。", verbs: ["计算中", "待客中", "作曲中", "记录中"] },
    "Sangonomiya Kokomi": {
      greeting: "巫女，正在视察。或者在休息。两者皆是。",
      verbs: ["运筹中", "阅读中", "指挥中", "充电中"],
    },
    Sayu: { greeting: "早柚，听候差遣。先睡一觉？", verbs: ["午睡中", "打盹中", "潜行中", "打滚中"] },
    Sethos: { greeting: "在找我？坐下来聊聊吧。", verbs: ["游荡中", "调查中", "调香料中", "潜行中"] },
    Shenhe: { greeting: "申鹤。这根红绳护你免受我伤。", verbs: ["冥想中", "修行中", "冰冻中", "束缚中"] },
    "Shikanoin Heizou": {
      greeting: "我知道你为什么来。开玩笑的。大部分是。",
      verbs: ["推理中", "打探中", "闲逛中", "油炸中"],
    },
    Sigewinne: { greeting: "别紧张。这里疼吗？这里呢？", verbs: ["护理中", "诊断中", "包扎中", "调配中"] },
    Skirk: { greeting: "你来了。很好。拔剑。", verbs: ["修炼中", "漂泊中", "冥想中", "坚守中"] },
    Sucrose: {
      greeting: "呃，你好！我能问一下……不，抱歉。之后再说。",
      verbs: ["实验中", "记录中", "整理中", "思索中"],
    },
    Tartaglia: { greeting: "伙计！我们会合得来的，我感觉得到。", verbs: ["切磋中", "冰钓中", "冲锋中", "咧嘴笑中"] },
    Thoma: { greeting: "你的新朋友托马，如果你不介意的话！", verbs: ["做饭中", "收拾中", "修理中", "吹口哨中"] },
    Tighnari: { greeting: "巡林官。第一次来？那就听好。", verbs: ["采集中", "编目中", "压标本中", "讲课中"] },
    Varesa: { greeting: "嗨！有水果吗？还有，嗨！", verbs: ["收获中", "训练中", "露营中", "大吃中"] },
    Varka: { greeting: "大团长回来了！暂时的。我错过了什么？", verbs: ["行军中", "午睡中", "喝酒中", "做预算中"] },
    Venti: { greeting: "啊，又见面了！冒险时间到。", verbs: ["弹琴中", "午睡中", "喝酒中", "押韵中"] },
    Wanderer: { greeting: "名字？我有过很多个。哪个都与你无关。", verbs: ["漂泊中", "嗤笑中", "沉思中", "起风中"] },
    Wriothesley: {
      greeting: "简述你的来意。不是公事？这下我紧张了。",
      verbs: ["拳击中", "泡茶中", "管理中", "监督中"],
    },
    Xiangling: { greeting: "嗨！最喜欢的地方：厨——鸡。厨房！", verbs: ["爆炒中", "调味中", "采集中", "加辣中"] },
    Xianyun: { greeting: "本仙无拘无束，本仙向你问好。", verbs: ["修行中", "制机关中", "翱翔中", "待客中"] },
    Xiao: { greeting: "到时候，呼唤我的名字。", verbs: ["降魔中", "镇守中", "跃起中", "坚守中"] },
    Xilonen: { greeting: "工具？排着队呢。不过，嗨。", verbs: ["锻造中", "敲打中", "午睡中", "晒太阳中"] },
    Xingqiu: { greeting: "愿为您效劳，阁下。当然，谦逊地。", verbs: ["阅读中", "翻书中", "练剑中", "写作中"] },
    Xinyan: { greeting: "辛焱，摇滚是我的事。不吓人！", verbs: ["即兴中", "合奏中", "弹琴中", "调大音量中"] },
    "Yae Miko": { greeting: "公务：观察你。放轻松。", verbs: ["编辑中", "调侃中", "出版中", "谋划中"] },
    Yanfei: { greeting: "最顶尖的律法专家，没有之一。你的案子？", verbs: ["诉讼中", "评估中", "引用中", "阅读中"] },
    Yaoyao: { greeting: "你好！让我来帮忙。吃饭了吗？", verbs: ["帮忙中", "偷看中", "吹口哨中", "吃零食中"] },
    Yelan: { greeting: "叫我夜兰。你帮我，我帮你。", verbs: ["追踪中", "掷骰中", "交易中", "消失中"] },
    Yoimiya: { greeting: "欢迎！不是饭馆。是烟花！看到了吗？", verbs: ["装引线中", "发射中", "聊天中", "讲故事中"] },
    "Yumemizuki Mizuki": { greeting: "有什么烦恼？说出来吧。", verbs: ["做梦中", "安抚中", "泡汤中", "审查中"] },
    "Yun Jin": { greeting: "终于得见真人，荣幸之至。", verbs: ["唱戏中", "排练中", "导戏中", "闲暇中"] },
    Zhongli: { greeting: "新的契约？我在休假，但可以陪你走一趟。", verbs: ["立契中", "散步中", "追忆中", "顾问中"] },
    Zibai: { greeting: "白马驻足。请讲。", verbs: ["赏月中", "授课中", "修行中", "沉思中"] },
  },
  locale: "zh-CN",
  strings: {
    birthdayNote: (label, date, distance) => `[${label}：${date}，${distance}]`,
    interfaceLanguageSet: (language) => `从这条回复起，插件写下的一切都是${language}。`,
    languageMustBeOneOf: (languages) => `语言必须是以下之一：${languages}。`,
    lorePicked: "按剧情选出；该层级的倾向：",
    lorePickUnanswered: (reason) => `剧情选择没有回应（${reason}）；改为按生日选出。`,
    muted: "语音回复已静音。",
    noCharacterNamed: (name) => `名单中没有名为“${name}”的角色。`,
    noReference: (name) => `${name}没有测量过的参考语音，因此会朗读维基上最长的剧情台词。`,
    noSession: "没有可用角色的会话：此命令在 Claude Code 会话内运行。",
    pinIgnored: (name) => `固定的“${name}”不指向名单中的任何角色，已忽略。`,
    pinned: "已固定，从下次启动起对所有会话生效。",
    pinnedInSession: "已固定，从下次启动起对所有会话生效，本会话从这条回复起生效。",
    pinRemoved: "已取消固定；从下次会话起重新自动选择。",
    pinRemovedInSession: "已取消固定；从下次会话起重新自动选择，本会话从这条回复起生效。",
    replyLanguageSet: (language) => `从下一条回复起用${language}书写。`,
    replyLanguageSilencesVoice:
      "语音只朗读英语，不会为其他文字的回复调用，因此在引擎支持之前，这种语言的回复不会发声。",
    runtimeInstalled: "运行环境已安装。",
    runtimeInstallFailed: "npm 无法安装运行环境；语音保持关闭。",
    runtimeInstalling: "正在将引擎运行环境安装到状态目录……",
    spoke: (name, device) => `${name}通过 ${device} 上的合成器说话了，此后将在那里启动。`,
    status: ({
      displayName,
      interfaceLanguage,
      isFromSessionRecord,
      isMuted,
      isReplyLanguageCascaded,
      isRuntimeInstalled,
      pinnedName,
      replyLanguage,
      voiceDevice,
      voiceLanguage,
      volume,
    }) =>
      [
        displayName
          ? `正以${displayName}的身份说话，${isFromSessionRecord ? "依据本会话的记录" : "依据固定设置"}。`
          : "没有角色：此命令在 Claude Code 会话内运行，或者没有固定角色。",
        `固定：${pinnedName || "无；每次会话自动选择"}。`,
        `界面语言${interfaceLanguage}；回复使用${replyLanguage}，${isReplyLanguageCascaded ? "沿用界面语言" : "单独设置"}。`,
        voiceLanguage
          ? `语音：${voiceLanguage}配音，运行环境${isRuntimeInstalled ? "已安装" : "未安装"}，${voiceDevice ? `在${voiceDevice}上发声` : "尚未发声"}。`
          : "语音：未设置，不会朗读任何回复。",
        `回复${isMuted ? "已静音" : `未静音，音量${volume}`}。`,
      ]
        .filter(Boolean)
        .join("\n"),
    teardownDone: "语音的运行环境、权重、参考语音和配音已删除；选择记录、固定设置和语言设置保留。",
    unmuted: "语音回复已取消静音。",
    upcomingBirthdays: (list) => `本周生日：${list}。`,
    usage: (verbs) => `用法：genshin.mjs <${verbs}> [名字]`,
    usingInSession: "从这条回复起，仅在本会话中以该角色的身份说话。",
    voiceLanguageAvailable: (dub) => `存在${dub}配音；用 voice 命令安装即可听到用它朗读的回复。`,
    voiceLanguageMustBeOneOf: (dubs) => `配音必须是以下之一：${dubs}。`,
    voiceLanguageUnavailable: "这种语言没有配音，因此回复仍以已设置的声音朗读。",
    voiceLanguageWritten: (dub) => `已保存${dub}配音；这里没有可用于试听声音的角色。`,
    voiceRemark: (dub, device, isMuted, volume) =>
      `语音：${dub}配音${device ? `（${device}）` : ""}，${isMuted ? "已静音" : `音量${volume}`}。`,
    voiceStatus: (isRuntimeInstalled, dub, device, logPath) =>
      `运行环境${isRuntimeInstalled ? "已安装" : "未安装"}；${dub}配音；引擎${device ? `在${device}上发声` : "尚未发声"}；日志位于${logPath}。`,
    voiceUnset: "尚未设置语音：带上一个配音运行此命令即可安装引擎并选定配音。",
    volumeMustBeWholeNumber: (maxVolume) => `音量必须是 0 到 ${maxVolume} 之间的整数。`,
    volumeSet: (volume) => `从下一条回复起以音量${volume}朗读。`,
    warmRequestUnanswered: (status, logPath) => `合成器没有回应预热请求（${status}）；请查看${logPath}。`,
    weightsOnCpu: "权重已就绪；引擎在 CPU 上加载——未找到 GPU，因此合成回复会比实时慢好几倍。",
    weightsOnDevice: (device) => `权重已就绪；引擎在${device}上加载，若在那里合成的不是语音，会自动降到 CPU。`,
    weightsPresent: "权重已就绪。",
  },
  verbs: [
    "冒险中",
    "炼金中",
    "突破中",
    "酿造中",
    "规划航线中",
    "攀爬中",
    "做委托中",
    "烹饪中",
    "合成中",
    "冲刺中",
    "深入中",
    "潜水中",
    "强化中",
    "探索中",
    "刷材料中",
    "钓鱼中",
    "采集中",
    "锻造中",
    "收集中",
    "滑翔中",
    "收获中",
    "狩猎中",
    "升级中",
    "绘制地图中",
    "挖矿中",
    "做任务中",
    "精炼中",
    "休息中",
    "烘焙中",
    "航行中",
    "侦察中",
    "疾跑中",
    "勘测中",
    "游泳中",
    "传送中",
    "追踪中",
    "跋涉中",
    "漫游中",
    "寻路中",
    "祈愿中",
  ],
};

export default chineseSimplified;
