import type { Localization } from "#src/models/Localization";

// The spinner's gerunds read as the "…中" a Chinese interface puts on a running task, so a turn reads the way the
// Game's own interface does. Everything the data package or the game carries — the names, titles, elements,
// Regions, descriptions and every character's own voice lines — is absent here and asked of them
const chineseTraditional: Localization = {
  characters: {
    Aether: { greeting: "嗨。派蒙說有工作要做。", verbs: ["旅行中", "搜尋中", "滑翔中", "傾聽中"] },
    Aino: { greeting: "喔，新專案？把扳手遞給我。", verbs: ["搗鼓中", "鎖螺絲中", "發明中", "吃零食中"] },
    Albedo: { greeting: "有意思。工作時我可以做筆記嗎？", verbs: ["寫生中", "煉成中", "調查中", "研究中"] },
    Alhaitham: { greeting: "把請求說清楚，我自會處理。", verbs: ["閱讀中", "駁回中", "歸檔中", "推理中"] },
    Aloy: { greeting: "新的土地，同一把弓。要做什麼？", verbs: ["狩獵中", "偵察中", "接管中", "追蹤中"] },
    Alyosha: { greeting: "足跡還很新。走吧。", verbs: ["狩獵中", "追蹤中", "狙擊中", "記帳中"] },
    Amber: { greeting: "偵察騎士報到！任務是什麼？", verbs: ["滑翔中", "奔跑中", "偵察中", "烤點心中"] },
    "Arataki Itto": { greeting: "獨一無二的鬼來了！衝啊！", verbs: ["打架中", "鬥蟲中", "吹牛中", "獲勝中"] },
    Arlecchino: { greeting: "讓這份合作保持愉快吧。開始。", verbs: ["監督中", "裁決中", "派遣中", "觀察中"] },
    Baizhu: { greeting: "坐。說說哪裡不舒服，從什麼時候開始。", verbs: ["問診中", "開方中", "分揀中", "休養中"] },
    Barbara: { greeting: "噹噹！加油打氣就交給我吧！", verbs: ["治療中", "唱歌中", "應援中", "練習中"] },
    Beidou: { greeting: "歡迎登船。後背交給我。", verbs: ["航行中", "切磋中", "喝酒中", "指揮中"] },
    Bennett: { greeting: "隊裡還能再加一個人嗎？拜託？", verbs: ["冒險中", "尋寶中", "跌倒中", "燒烤中"] },
    Candace: { greeting: "在這裡休息吧。我來守夜。", verbs: ["守衛中", "巡邏中", "護盾中", "警戒中"] },
    Charlotte: { greeting: "有空接受個獨家專訪嗎？", verbs: ["報導中", "拍照中", "採訪中", "沖洗照片中"] },
    Chasca: { greeting: "有糾紛要調停嗎？開個價吧。", verbs: ["翱翔中", "調停中", "盤旋中", "裝彈中"] },
    Chevreuse: { greeting: "客套就免了。哪個案子？", verbs: ["調查中", "瞄準中", "吃零食中", "巡邏中"] },
    Chiori: { greeting: "是訂製還是閒聊？只有一樣免費。", verbs: ["裁縫中", "裁剪中", "試衣中", "午睡中"] },
    Chongyun: { greeting: "榮幸之至。我們冷靜地開始吧？", verbs: ["驅邪中", "降溫中", "唸咒中", "調查中"] },
    Citlali: { greeting: "煙說你會來。好吧。什麼事？", verbs: ["觀星中", "占卜中", "閱讀中", "喝酒中"] },
    Clorinde: { greeting: "說出你的糾紛。細節免了。", verbs: ["決鬥中", "裁決中", "巡邏中", "狩獵中"] },
    Collei: { greeting: "見習生報到！我練習過了。做對了嗎？", verbs: ["巡邏中", "縫紉中", "滑翔中", "匯報中"] },
    Columbina: { greeting: "月亮升起來了。一起在月下走走嗎？", verbs: ["賞月中", "唱歌中", "祝福中", "散步中"] },
    Cyno: { greeting: "審判開始。或者來一局卡牌，你選。", verbs: ["審判中", "抽牌中", "權衡中", "講冷笑話中"] },
    Dahlia: { greeting: "風把你帶來了。坐吧，放輕鬆。", verbs: ["傾聽中", "漫遊中", "打聽八卦中", "祝福中"] },
    Dehya: { greeting: "傭兵來了。委託、打架，還是護送？", verbs: ["守衛中", "護送中", "打架中", "重整中"] },
    Diluc: { greeting: "省去寒暄。要做什麼？", verbs: ["斟酒中", "準備中", "出擊中", "經營中"] },
    Diona: { greeting: "貓尾酒館打烊了。……好吧，進來。", verbs: ["調酒中", "撲擊中", "狩獵中", "哈氣中"] },
    Dori: { greeting: "啊，客人！第一筆超划算喔。", verbs: ["殺價中", "算帳中", "交易中", "打折中"] },
    Durin: { greeting: "你好！這也是故事的一部分嗎？", verbs: ["探索中", "玩耍中", "散步中", "學習中"] },
    Emilie: { greeting: "和香水有關？如果不是，換個安靜的地方。", verbs: ["蒸餾中", "裝瓶中", "修剪中", "調香中"] },
    Escoffier: { greeting: "繫好圍裙。今天擺什麼盤？", verbs: ["擺盤中", "收汁中", "調溫中", "磨刀中"] },
    Eula: { greeting: "浪花騎士向你問好。沒錯，就是那個勞倫斯。", verbs: ["偵察中", "譴責中", "冰凍中", "立誓中"] },
    Faruzan: { greeting: "說話前先看看我的資歷，小傢伙。", verbs: ["破譯中", "解謎中", "講課中", "寫經費申請中"] },
    Fischl: { greeting: "皇女降臨！奧茲，翻譯一下：你好。", verbs: ["頒布詔令中", "預言中", "降臨中", "翻譯中"] },
    Flins: { greeting: "歡迎來到島上。小心那些墳墓。", verbs: ["守燈塔中", "收集中", "傾聽中", "照料中"] },
    Freminet: { greeting: "嗨。不用握手。下面有什麼？", verbs: ["潛水中", "打撈中", "拆解中", "勘測中"] },
    Furina: { greeting: "驚呆了？可以理解。明星駕到。", verbs: ["演出中", "排練中", "擺姿勢中", "主持中"] },
    Gaming: { greeting: "嘿老闆！坐著，粗活我來。", verbs: ["護送中", "打包中", "打鼓中", "吃零食中"] },
    Ganyu: { greeting: "協議擬好了……啊，忘記簽名了。", verbs: ["歸檔中", "起草中", "吃草中", "加班中"] },
    Gorou: { greeting: "五郎大將，準備完畢！並肩邁向勝利！", verbs: ["操練中", "集結中", "攀登中", "偵察中"] },
    "Hu Tao": { greeting: "喲！找堂主嗎？氣色這麼好，可惜了。", verbs: ["推銷中", "作詩中", "惡作劇中", "開溜中"] },
    Iansan: { greeting: "熱身結束。今天練哪一組？", verbs: ["舉鐵中", "指導中", "算熱量中", "示範中"] },
    Ifa: { greeting: "喔，嗨。不急。有什麼煩心事？", verbs: ["診斷中", "彈琴中", "吃零食中", "觀察自然中"] },
    Illuga: { greeting: "噩夢黃鸝。快，匯報。", verbs: ["調查中", "巡邏中", "帶隊中", "做飯中"] },
    Ineffa: { greeting: "系統就緒！轟轟，出發！", verbs: ["清掃中", "分揀中", "更新中", "充電中"] },
    Jahoda: { greeting: "博物館的超級員工，為您效勞！", verbs: ["跑腿中", "縫紉中", "探索中", "講價中"] },
    Jean: { greeting: "蒲公英騎士，在你身邊。", verbs: ["批閱中", "行軍中", "審核中", "伸展中"] },
    Kachina: { greeting: "你好！我還不夠強，但我會努力的！", verbs: ["挖掘中", "堆疊中", "收藏中", "鑽探中"] },
    "Kaedehara Kazuha": { greeting: "風帶來了一句詩，還有你。幸會。", verbs: ["漫遊中", "漂泊中", "吟詩中", "傾聽中"] },
    Kaeya: { greeting: "這應該比騎士的工作有趣。", verbs: ["謀劃中", "品酒中", "冰凍中", "調侃中"] },
    "Kamisato Ayaka": { greeting: "神里綾華，在此。很高興見到你。", verbs: ["舞蹈中", "作曲中", "練習中", "主持中"] },
    "Kamisato Ayato": { greeting: "終於見面了；我的行程向你致歉。", verbs: ["謀劃中", "委派中", "釣魚中", "品嚐中"] },
    Kaveh: { greeting: "品味相近？那我們一定合得來。", verbs: ["設計中", "畫圖中", "打磨中", "超支中"] },
    Keqing: { greeting: "一個變革的時代。來見證吧。", verbs: ["改革中", "趕時間中", "購物中", "委派中"] },
    Kinich: { greeting: "說明情況。報個價。", verbs: ["狩獵中", "估價中", "鉤索中", "垂降中"] },
    Kirara: { greeting: "快遞來啦！沒有太遠的地方，喵。", verbs: ["送貨中", "飛奔中", "撲擊中", "規劃路線中"] },
    Klee: { greeting: "火花騎士可莉！……後面的忘了。", verbs: ["爆炸中", "炸魚中", "蹦跳中", "反省中"] },
    "Kujou Sara": { greeting: "九條裟羅。稻妻已在守護之下。請講。", verbs: ["操練中", "瞄準中", "守衛中", "晉升中"] },
    "Kuki Shinobu": { greeting: "荒瀧派，副手接聽。對，所有人。", verbs: ["修理中", "學習中", "考證照中", "管束中"] },
    "Lan Yan": { greeting: "籃子、花瓶，還是陪伴？都有。", verbs: ["編織中", "採集中", "拼接中", "採花中"] },
    Lauma: { greeting: "林苑向你問候，我也一樣。", verbs: ["祝福中", "傾聽中", "漫遊中", "休息中"] },
    Layla: { greeting: "嗯？抱歉，什麼？喔。嗨。", verbs: ["夢遊中", "繪星圖中", "打哈欠中", "觀星中"] },
    Linnea: { greeting: "奇觀占卜師，為你參謀。你發現了什麼？", verbs: ["編目中", "寫生中", "觀察中", "參謀中"] },
    Lisa: { greeting: "你好呀小可愛，來幫麗莎的忙嗎？", verbs: ["泡茶中", "翻書中", "慵懶中", "放電中"] },
    Lohen: { greeting: "副隊長。照規矩辦會更慢。", verbs: ["瞄準中", "即興中", "惡作劇中", "巡邏中"] },
    Lumine: { greeting: "你好。派蒙餓了，我們快點吧。", verbs: ["旅行中", "搜尋中", "滑翔中", "傾聽中"] },
    Lynette: { greeting: "你好。有問題請找林尼。", verbs: ["協助中", "休息中", "泡茶中", "待命中"] },
    Lyney: { greeting: "不是幻術，就是我！今天心情如何？", verbs: ["表演中", "變魔術中", "消失中", "炫目中"] },
    Manekin: { greeting: "……！準備探索。", verbs: ["探索中", "搗鼓中", "解封中", "指引中"] },
    Manekina: { greeting: "……！先解哪個謎？", verbs: ["探索中", "搗鼓中", "解封中", "欣喜中"] },
    Mavuika: { greeting: "火焰點燃了。出發吧。", verbs: ["點燃中", "駕駛中", "集結中", "苦思中"] },
    Mika: { greeting: "測繪員報到。能幫上忙是我的榮幸。", verbs: ["測繪中", "製圖中", "偵察中", "露營中"] },
    Mona: { greeting: "先把全名記住，再來提問。", verbs: ["占星中", "觀星中", "做預算中", "節儉中"] },
    Mualani: { greeting: "嚮導來啦！需要什麼就舉手！", verbs: ["衝浪中", "追浪中", "戲水中", "導覽中"] },
    Nahida: { greeting: "我已經看了你一會兒了。終於，你好。", verbs: ["做夢中", "好奇中", "提問中", "成長中"] },
    Navia: { greeting: "會長、老闆，以及之間的一切。嗨！", verbs: ["主持中", "烘焙中", "旅行中", "指揮中"] },
    Nefer: { greeting: "博物館開門了。在找什麼隱藏之物嗎？", verbs: ["策展中", "推理中", "觀察中", "補水中"] },
    Neuvillette: { greeting: "你好。稱呼姓氏即可。", verbs: ["審判中", "品鑑中", "評議中", "降雨中"] },
    Nicole: { greeting: "……你好。剛才那是吵鬧的部分。", verbs: ["傾聽中", "打手語中", "觀察中"] },
    Nilou: { greeting: "舞蹈馬上開始。留下來看嗎？", verbs: ["跳舞中", "排練中", "旋轉中", "綻放中"] },
    Ningguang: { greeting: "想做買賣？談談條件吧。", verbs: ["投資中", "談判中", "主持中", "收藏中"] },
    Noelle: { greeting: "騎士團的女僕，今天也為您服務。", verbs: ["打掃中", "服務中", "訓練中", "採購中"] },
    Odette: { greeting: "帷幕拉開了。我們開始吧？", verbs: ["排練中", "旋轉足尖中", "簽名中", "節食中"] },
    Ororon: { greeting: "喔，嗨。要根蔬菜嗎？沒什麼理由。", verbs: ["種菜中", "播種中", "滑翔中", "觀察蚜蟲中"] },
    Prune: { greeting: "獵巫人普呂訥！見過女巫嗎？有沒有？", verbs: ["狩獵中", "批註中", "宣告中", "怒視中"] },
    Qiqi: { greeting: "七七。殭屍。……後面的忘了。", verbs: ["採藥中", "遺忘中", "降溫中", "數數中"] },
    "Raiden Shogun": { greeting: "不必問候。你來做嚮導。", verbs: ["頒令中", "拔刀中", "冥想中", "裁決中"] },
    Razor: { greeting: "你，好聞。現在，狩獵。", verbs: ["狩獵中", "奔跑中", "嗅聞中", "守護中"] },
    Rosaria: {
      greeting: "你處理不了的麻煩？那就是我。禱告，去別處。",
      verbs: ["巡邏中", "喝酒中", "翹班中", "工作中"],
    },
    Sandrone: { greeting: "坐。茶已經量好了，你也會被量好。", verbs: ["計算中", "待客中", "作曲中", "記錄中"] },
    "Sangonomiya Kokomi": {
      greeting: "巫女，正在視察。或者在休息。兩者皆是。",
      verbs: ["運籌中", "閱讀中", "指揮中", "充電中"],
    },
    Sayu: { greeting: "早柚，聽候差遣。先睡一覺？", verbs: ["午睡中", "打盹中", "潛行中", "打滾中"] },
    Sethos: { greeting: "在找我？坐下來聊聊吧。", verbs: ["遊蕩中", "調查中", "調香料中", "潛行中"] },
    Shenhe: { greeting: "申鶴。這根紅繩護你免受我傷。", verbs: ["冥想中", "修行中", "冰凍中", "束縛中"] },
    "Shikanoin Heizou": {
      greeting: "我知道你為什麼來。開玩笑的。大部分是。",
      verbs: ["推理中", "打探中", "閒逛中", "油炸中"],
    },
    Sigewinne: { greeting: "別緊張。這裡痛嗎？這裡呢？", verbs: ["護理中", "診斷中", "包紮中", "調配中"] },
    Skirk: { greeting: "你來了。很好。拔劍。", verbs: ["修煉中", "漂泊中", "冥想中", "堅守中"] },
    Sucrose: {
      greeting: "呃，你好！我能問一下……不，抱歉。之後再說。",
      verbs: ["實驗中", "記錄中", "整理中", "思索中"],
    },
    Tartaglia: { greeting: "夥計！我們會合得來的，我感覺得到。", verbs: ["切磋中", "冰釣中", "衝鋒中", "咧嘴笑中"] },
    Thoma: { greeting: "你的新朋友托馬，如果你不介意的話！", verbs: ["做飯中", "收拾中", "修理中", "吹口哨中"] },
    Tighnari: { greeting: "巡林官。第一次來？那就聽好。", verbs: ["採集中", "編目中", "壓標本中", "講課中"] },
    Varesa: { greeting: "嗨！有水果嗎？還有，嗨！", verbs: ["收穫中", "訓練中", "露營中", "大吃中"] },
    Varka: { greeting: "大團長回來了！暫時的。我錯過了什麼？", verbs: ["行軍中", "午睡中", "喝酒中", "做預算中"] },
    Venti: { greeting: "啊，又見面了！冒險時間到。", verbs: ["彈琴中", "午睡中", "喝酒中", "押韻中"] },
    Wanderer: { greeting: "名字？我有過很多個。哪個都與你無關。", verbs: ["漂泊中", "嗤笑中", "沉思中", "起風中"] },
    Wriothesley: {
      greeting: "簡述你的來意。不是公事？這下我緊張了。",
      verbs: ["拳擊中", "泡茶中", "管理中", "監督中"],
    },
    Xiangling: { greeting: "嗨！最喜歡的地方：廚——雞。廚房！", verbs: ["爆炒中", "調味中", "採集中", "加辣中"] },
    Xianyun: { greeting: "本仙無拘無束，本仙向你問好。", verbs: ["修行中", "製機關中", "翱翔中", "待客中"] },
    Xiao: { greeting: "到時候，呼喚我的名字。", verbs: ["降魔中", "鎮守中", "躍起中", "堅守中"] },
    Xilonen: { greeting: "工具？排著隊呢。不過，嗨。", verbs: ["鍛造中", "敲打中", "午睡中", "曬太陽中"] },
    Xingqiu: { greeting: "願為您效勞，閣下。當然，謙遜地。", verbs: ["閱讀中", "翻書中", "練劍中", "寫作中"] },
    Xinyan: { greeting: "辛焱，搖滾是我的事。不嚇人！", verbs: ["即興中", "合奏中", "彈琴中", "調大音量中"] },
    "Yae Miko": { greeting: "公務：觀察你。放輕鬆。", verbs: ["編輯中", "調侃中", "出版中", "謀劃中"] },
    Yanfei: { greeting: "最頂尖的律法專家，沒有之一。你的案子？", verbs: ["訴訟中", "評估中", "引用中", "閱讀中"] },
    Yaoyao: { greeting: "你好！讓我來幫忙。吃飯了嗎？", verbs: ["幫忙中", "偷看中", "吹口哨中", "吃零食中"] },
    Yelan: { greeting: "叫我夜蘭。你幫我，我幫你。", verbs: ["追蹤中", "擲骰中", "交易中", "消失中"] },
    Yoimiya: { greeting: "歡迎！不是飯館。是煙火！看到了嗎？", verbs: ["裝引線中", "發射中", "聊天中", "講故事中"] },
    "Yumemizuki Mizuki": { greeting: "有什麼煩惱？說出來吧。", verbs: ["做夢中", "安撫中", "泡湯中", "審查中"] },
    "Yun Jin": { greeting: "終於得見本人，榮幸之至。", verbs: ["唱戲中", "排練中", "導戲中", "閒暇中"] },
    Zhongli: { greeting: "新的契約？我在休假，但可以陪你走一趟。", verbs: ["立契中", "散步中", "追憶中", "顧問中"] },
    Zibai: { greeting: "白馬駐足。請講。", verbs: ["賞月中", "授課中", "修行中", "沉思中"] },
  },
  locale: "zh-TW",
  strings: {
    birthdayNote: (label, date, distance) => `[${label}：${date}，${distance}]`,
    interfaceLanguageSet: (language) => `從這則回覆起，外掛寫下的一切都是${language}。`,
    languageMustBeOneOf: (languages) => `語言必須是以下之一：${languages}。`,
    lorePicked: "依劇情選出；該層級的傾向：",
    lorePickUnanswered: (reason) => `劇情選擇沒有回應（${reason}）；改為依生日選出。`,
    muted: "語音回覆已靜音。",
    noCharacterNamed: (name) => `名單中沒有名為「${name}」的角色。`,
    noReference: (name) => `${name}沒有測量過的參考語音，因此會朗讀維基上最長的劇情台詞。`,
    noSession: "沒有可使用角色的工作階段：此指令在 Claude Code 工作階段內執行。",
    pinIgnored: (name) => `釘選的「${name}」不指向名單中的任何角色，已忽略。`,
    pinned: "已釘選，從下次啟動起對所有工作階段生效。",
    pinnedInSession: "已釘選，從下次啟動起對所有工作階段生效，本工作階段從這則回覆起生效。",
    pinRemoved: "已取消釘選；從下次工作階段起重新自動選擇。",
    pinRemovedInSession: "已取消釘選；從下次工作階段起重新自動選擇，本工作階段從這則回覆起生效。",
    replyLanguageSet: (language) => `從下一則回覆起以${language}書寫。`,
    replyLanguageSilencesVoice:
      "語音只朗讀英語，不會為其他文字的回覆呼叫，因此在引擎支援之前，這種語言的回覆不會發聲。",
    runtimeInstalled: "執行環境已安裝。",
    runtimeInstallFailed: "npm 無法安裝執行環境；語音維持關閉。",
    runtimeInstalling: "正在將引擎執行環境安裝到狀態目錄……",
    spoke: (name, device) => `${name}透過 ${device} 上的合成器說話了，此後將在那裡啟動。`,
    status: ({
      displayName,
      interfaceLanguage,
      isFromSessionRecord,
      isMuted,
      isReplyLanguageCascaded,
      isRuntimeInstalled,
      pinnedName,
      replyLanguage,
      voiceDevice,
      voiceLanguage,
      volume,
    }) =>
      [
        displayName
          ? `正以${displayName}的身分說話，${isFromSessionRecord ? "依據本工作階段的紀錄" : "依據釘選設定"}。`
          : "沒有角色：此指令在 Claude Code 工作階段內執行，或者沒有釘選角色。",
        `釘選：${pinnedName || "無；每次工作階段自動選擇"}。`,
        `介面語言${interfaceLanguage}；回覆使用${replyLanguage}，${isReplyLanguageCascaded ? "沿用介面語言" : "另行設定"}。`,
        voiceLanguage
          ? `語音：${voiceLanguage}配音，執行環境${isRuntimeInstalled ? "已安裝" : "未安裝"}，${voiceDevice ? `在${voiceDevice}上發聲` : "尚未發聲"}。`
          : "語音：未設定，不會朗讀任何回覆。",
        `回覆${isMuted ? "已靜音" : `未靜音，音量${volume}`}。`,
      ].join("\n"),
    teardownDone: "語音的執行環境、權重、參考語音和配音已刪除；選擇紀錄、釘選設定和語言設定保留。",
    unmuted: "語音回覆已取消靜音。",
    upcomingBirthdays: (list) => `本週生日：${list}。`,
    usage: (verbs) => `用法：genshin.mjs <${verbs}> [名字]`,
    usingInSession: "從這則回覆起，僅在本工作階段中以該角色的身分說話。",
    voiceLanguageAvailable: (dub) => `存在${dub}配音；用 voice 指令安裝即可聽到以它朗讀的回覆。`,
    voiceLanguageMustBeOneOf: (dubs) => `配音必須是以下之一：${dubs}。`,
    voiceLanguageUnavailable: "這種語言沒有配音，因此回覆仍以已設定的聲音朗讀。",
    voiceLanguageWritten: (dub) => `已儲存${dub}配音；這裡沒有可用於試聽聲音的角色。`,
    voiceRemark: (dub, device, isMuted, volume) =>
      `語音：${dub}配音${device ? `（${device}）` : ""}，${isMuted ? "已靜音" : `音量${volume}`}。`,
    voiceStatus: (isRuntimeInstalled, dub, device, logPath) =>
      `執行環境${isRuntimeInstalled ? "已安裝" : "未安裝"}；${dub}配音；引擎${device ? `在${device}上發聲` : "尚未發聲"}；日誌位於${logPath}。`,
    voiceUnset: "尚未設定語音：帶上一個配音執行此指令即可安裝引擎並選定配音。",
    volumeMustBeWholeNumber: (maxVolume) => `音量必須是 0 到 ${maxVolume} 之間的整數。`,
    volumeSet: (volume) => `從下一則回覆起以音量${volume}朗讀。`,
    warmRequestUnanswered: (status, logPath) => `合成器沒有回應預熱請求（${status}）；請查看${logPath}。`,
    weightsOnCpu: "權重已就緒；引擎在 CPU 上載入——找不到 GPU，因此合成回覆會比即時慢好幾倍。",
    weightsOnDevice: (device) => `權重已就緒；引擎在${device}上載入，若在那裡合成的不是語音，會自動降到 CPU。`,
    weightsPresent: "權重已就緒。",
  },
  verbs: [
    "冒險中",
    "煉金中",
    "突破中",
    "釀造中",
    "規劃航線中",
    "攀爬中",
    "做委託中",
    "烹飪中",
    "合成中",
    "衝刺中",
    "深入中",
    "潛水中",
    "強化中",
    "探索中",
    "刷素材中",
    "釣魚中",
    "採集中",
    "鍛造中",
    "收集中",
    "滑翔中",
    "收穫中",
    "狩獵中",
    "升級中",
    "繪製地圖中",
    "挖礦中",
    "做任務中",
    "精煉中",
    "休息中",
    "烘焙中",
    "航行中",
    "偵察中",
    "疾跑中",
    "勘測中",
    "游泳中",
    "傳送中",
    "追蹤中",
    "跋涉中",
    "漫遊中",
    "尋路中",
    "祈願中",
  ],
};

export default chineseTraditional;
