import { MAX_INPUT_SENSITIVITY_DECIBELS, MIN_INPUT_SENSITIVITY_DECIBELS } from "@esposter/db-schema";

export const SETTINGS_CONTENT_ID = "settings-content";
export const INPUT_SENSITIVITY_DECIBELS_RANGE = MAX_INPUT_SENSITIVITY_DECIBELS - MIN_INPUT_SENSITIVITY_DECIBELS;
