[build.nixpacksPlan.phases.setup]
nixPkgs = ['...', 'pnpm-9_x']

[build.nixpacksPlan.phases.install]
dependsOn = ["setup"]
cmds = ["pnpm i"]

[build]
buildCommand = "pnpm build"

[deploy]
startCommand = "pnpm start"