import type { Task } from "tinybench";

import { createSandbox } from "@/services/sandbox/createSandbox";
import { InvalidOperationError, Operation } from "@esposter/shared";
import { spawn } from "node:child_process";
import { mkdir, writeFile } from "node:fs/promises";
import { arch, cpus, platform, release, totalmem } from "node:os";
import { dirname, resolve } from "node:path";
import process from "node:process";
import { Bench } from "tinybench";
// Speed-gate harness (specs/benchmarking.md). The rule: a sandbox path that loses to the native
// Baseline has negative value. With the native passthrough backend the two are expected to tie —
// This proves the measurement works, not a win yet. Real backends report a matrix of cache states
// Over a repo corpus here; for now it is one command, native vs sandbox, timed by tinybench.
// Results are written to a committed bench/results.md so a regression shows up in a diff over time.
const NATIVE = "native";
const SANDBOX = "sandbox";
const COMMAND = `node -e "process.stdout.write('bench')"`;
const ITERATIONS = 10;
const RESULTS_FILE = resolve(import.meta.dirname, "../../bench/results.md");
// CI-enforcement is deferred until a real backend can actually regress (deferred/ci-bench-gate.md);
// Until then the verdict is reported, never fatal.
const REGRESSION_RATIO = 1.1;

const runNative = (): Promise<void> =>
  new Promise((resolve, reject) => {
    const child = spawn(COMMAND, { shell: true, stdio: "ignore" });
    child.on("error", reject);
    child.on("close", () => {
      resolve();
    });
  });

const latencyOf = (task: Task) => {
  const { result } = task;
  if (result === undefined || !("latency" in result))
    throw new InvalidOperationError(Operation.Read, task.name, "benchmark produced no latency result");
  return result.latency;
};

const readMetadata = (): string => {
  const cpu = cpus();
  const gibibytes = (totalmem() / 1024 ** 3).toFixed(1);
  return [
    `- Date: ${new Date().toISOString()}`,
    `- Node: ${process.version}`,
    `- OS: ${platform()} ${release()} (${arch()})`,
    `- CPU: ${cpu[0]?.model ?? "unknown"} × ${cpu.length}`,
    `- RAM: ${gibibytes} GiB`,
  ].join("\n");
};

const formatResults = (tasks: Task[], ratio: number, isRegression: boolean): string => {
  const rows = tasks.map((task) => {
    const { mean, p99, samplesCount, sd } = latencyOf(task);
    return `| ${task.name} | ${mean.toFixed(2)} | ${sd.toFixed(2)} | ${p99.toFixed(2)} | ${samplesCount} |`;
  });
  return [
    "# sandbox-runtime — Benchmark results",
    "",
    "Generated by `pnpm bench` — the source of truth for tracking perf over time. Regenerate before",
    "Committing and diff the ratio. Numbers are machine-dependent (one dev's host today; CI Linux",
    "Numbers will differ), so only compare runs from the same environment.",
    "",
    "## Environment",
    "",
    readMetadata(),
    "",
    "## Latency (ms, lower is better)",
    "",
    `Command: \`${COMMAND}\` over ${ITERATIONS} iterations.`,
    "",
    "| task | mean | sd | p99 | samples |",
    "| ---- | ---- | -- | --- | ------- |",
    ...rows,
    "",
    `Ratio (sandbox/native): ${ratio.toFixed(2)}x — ${isRegression ? "REGRESSION" : "OK"}`,
    "",
  ].join("\n");
};

const sandbox = await createSandbox();
const bench = new Bench({ iterations: ITERATIONS, warmup: true });
bench.add(NATIVE, runNative);
bench.add(SANDBOX, () => sandbox.exec(COMMAND));
await bench.run();
await sandbox.dispose();

const meanByName = new Map(bench.tasks.map((task) => [task.name, latencyOf(task).mean]));
const ratio = (meanByName.get(SANDBOX) ?? 0) / (meanByName.get(NATIVE) ?? 1);
const isRegression = ratio > REGRESSION_RATIO;
const markdown = formatResults(bench.tasks, ratio, isRegression);
try {
  await mkdir(dirname(RESULTS_FILE), { recursive: true });
  await writeFile(RESULTS_FILE, markdown);
} catch (error) {
  throw new InvalidOperationError(
    Operation.Create,
    RESULTS_FILE,
    error instanceof Error ? error.message : String(error),
  );
}
process.stdout.write(markdown);
