// Room for a frame's wanted, drawn or surrounding tiles: the tiles all round the eye are a few hundred
export const TILE_SELECTION_CAPACITY = 512;
// Tiles are generated by a small pool of workers, a few at a time, and as many are kept as a selection holds, so every
// Tile round the eye stays held whichever way the camera turns, with room left for the ground it moved on from
export const TERRAIN_WORKER_COUNT = 2;
export const MAX_PENDING_TILE_COUNT = 8;
export const MAX_CACHED_TILE_COUNT = TILE_SELECTION_CAPACITY;
// Past a kilometre from the scene's origin the world is moved back under the camera, in steps of a coarsest tile so
// Every tile edge stays on a whole number
export const ORIGIN_SHIFT_THRESHOLD = 1024;
export const ORIGIN_SHIFT_STEP = 512;
// The square of water kept under the camera, wide enough to reach past where the fog closes on every side
export const WATER_SURFACE_SIZE = 3200;
// The ground the grass reads its footing from: a square past the middle ring's reach at a third of a metre a texel,
// Redrawn once the camera has crossed an eighth of it. A blade has a root, a middle and a tip
export const GRASS_CAPTURE_SIZE = 160;
export const GRASS_CAPTURE_RESOLUTION = 512;
export const GRASS_RECAPTURE_DISTANCE = 20;
export const GRASS_BLADE_SEGMENT_COUNT = 3;
// How far the clouds drift for a unit of wind, in cloud-layer units a second
export const CLOUD_DRIFT_PER_WIND = 0.012;
// A region's data is fetched once the camera is within this distance of one of its areas' outlines, in metres, and
// Reach is rechecked each time the camera has moved this far
export const REGION_REACH = 1500;
export const REGION_RECHECK_DISTANCE = 64;
// A region's fetch is abandoned as failed past this, so a stalled request cannot hold the world from being ready
export const REGION_FETCH_TIMEOUT_MS = 10_000;
// How far the tuning panel moves a grade's tint each way, and a tint's channels by the tuple key it writes through
export const TUNING_TINT_RANGE = 0.1;
export const TUNING_TINT_CHANNELS = [
  { key: "0", name: "red" },
  { key: "1", name: "green" },
  { key: "2", name: "blue" },
] as const;
