// Room for a frame's wanted, drawn or surrounding tiles: the tiles all round the eye are a few hundred
export const TILE_SELECTION_CAPACITY = 512;
// Tiles are generated by a small pool of workers, a few at a time, and as many are kept as a selection holds, so every
// Tile round the eye stays held whichever way the camera turns, with room left for the ground it moved on from
export const TERRAIN_WORKER_COUNT = 2;
export const MAX_PENDING_TILE_COUNT = 8;
// Past a kilometre from the scene's origin the world is moved back under the camera, in steps of a coarsest tile so
// Every tile edge stays on a whole number
export const ORIGIN_SHIFT_THRESHOLD = 1024;
export const ORIGIN_SHIFT_STEP = 512;
// The square of water kept under the camera, wide enough to reach past where the fog closes on every side
export const WATER_SURFACE_SIZE = 3200;
// The ground the grass reads its footing from: a square past the middle ring's reach at a third of a metre a texel,
// Redrawn once the camera has crossed an eighth of it. A blade has a root, a middle and a tip
export const GRASS_CAPTURE_SIZE = 160;
export const GRASS_CAPTURE_RESOLUTION = 512;
export const GRASS_RECAPTURE_DISTANCE = 20;
export const GRASS_BLADE_SEGMENT_COUNT = 3;
// How far the clouds drift for a unit of wind, in cloud-layer units a second
export const CLOUD_DRIFT_PER_WIND = 0.012;
// A region's data is fetched once the camera is within this distance of one of its areas' outlines, in metres, and
// Reach is rechecked each time the camera has moved this far
export const REGION_REACH = 1500;
export const REGION_RECHECK_DISTANCE = 64;
// An area with several weathers turns to its next one each this many seconds, a special climate holding its one.
// Provisional: read off the game's own weather schedule once a recording of a weather turning over minutes is in
export const AREA_WEATHER_CHANGE_SECONDS = 300;
// A fetch of the world's data, a region's or a game table's, is abandoned as failed past this, so a stalled request
// Cannot hold the world from being ready
export const DATA_FETCH_TIMEOUT_MS = 10_000;
// A failed read the world repeats on its own, since nothing the player does repeats it, is read again this long after
export const DATA_FETCH_RETRY_MS = 5000;
// How far the tuning panel moves a grade's tint each way, and a tint's channels by the tuple key it writes through
export const TUNING_TINT_RANGE = 0.1;
export const TUNING_TINT_CHANNELS = [
  { key: "0", name: "red" },
  { key: "1", name: "green" },
  { key: "2", name: "blue" },
] as const;
// The character's body and the free camera move in fixed steps of a sixtieth of a second, so a motion is the same at any
// Frame rate
export const FIXED_STEP_SECONDS = 1 / 60;
// The seed of the world's one seeded random source, which every roll the combat and the kit make draws on, so a session's
// Rolls repeat
export const WORLD_RANDOM_SEED = 1;
// The frame priority what moves the camera runs at, ahead of the floating origin's shift at TresJS's default of none,
// Whatever order it mounts in, so the shift reads where the camera now stands
export const CAMERA_FRAME_PRIORITY = -1;
// The frame priority what decides whether the sun's shadows are drawn again runs at, after the sky has turned the sun
// And the camera and the floating origin have moved, so the decision reads where each now stands
export const SHADOW_FRAME_PRIORITY = 1;
// The nearest cascades, the only ones the character's body casts into: the cascades past them are split from ground that a
// Body's shadow, a few metres long at this sun, never reaches, so a walk leaves them drawn
export const BODY_SHADOW_CASCADES = 2;
// The numbers an enemy's pose is kept as, its position's x and z and its heading, for the sun's shadows to tell an
// Enemy has moved since they were drawn
export const ENEMY_POSE_LENGTH = 3;
// How far an enemy must walk, in metres, or turn, in radians, from where its shadow was last drawn before the shadow is drawn
// Again: a quarter of a metre is about as far as a shadow's edge can stand out from the body that casts it, and an enemy
// Stepping less than that is a moving edge the eye does not follow
export const CASTER_REDRAW_DISTANCE = 0.25;
export const CASTER_REDRAW_ANGLE = 0.1;
// The colour the capsule a character's body is drawn as where no model stands on it, a pale stone the eye finds
export const CHARACTER_PLACEHOLDER_COLOR = 0xe8e2d4;
