export const RoutePath = {
  About: "/about",
  Anime: "/anime",
  Calendar: "/calendar",
  Clicker: "/clicker",
  Dashboard: "/dashboard",
  DashboardEditor: "/dashboard/editor",
  Docs: "/docs",
  Dungeons: "/dungeons",
  EmailEditor: "/email-editor",
  FlowchartEditor: "/flowchart-editor",
  Github: "https://github.com/Esposter/Esposter",
  Index: "/",
  Login: "/login",
  Messages: (id: string) => `/messages/${id}`,
  MessagesIndex: "/messages",
  MessagesInvite: (code: string) => `/messages/invite/${code}`,
  MessagesMessage: (id: string, rowKey: string) => `/messages/${id}/${rowKey}`,
  Post: (id: string) => `/post/${id}`,
  PostCreate: "/post/create",
  PostUpdate: (id: string) => `/post/update/${id}`,
  PrivacyPolicy: "/privacy-policy",
  Survey: (id: string) => `/surveyer/${id}`,
  Surveyer: "/surveyer",
  TableEditor: "/table-editor",
  UserSettings: "/user/settings",
  WebpageEditor: "/webpage-editor",
} as const;
export type RoutePath = typeof RoutePath;
