export enum StateName {
  Battle = "Battle",
  BringOutMonster = "BringOutMonster",
  CatchMonster = "CatchMonster",
  EnemyAttack = "EnemyAttack",
  EnemyInput = "EnemyInput",
  EnemyPostAttackCheck = "EnemyPostAttackCheck",
  Finished = "Finished",
  FleeAttempt = "FleeAttempt",
  GainExperience = "GainExperience",
  Intro = "Intro",
  ItemAttempt = "ItemAttempt",
  PlayerAttack = "PlayerAttack",
  PlayerInput = "PlayerInput",
  PlayerPostAttackCheck = "PlayerPostAttackCheck",
  PreBattleInfo = "PreBattleInfo",
  SwitchAttempt = "SwitchAttempt",
  SwitchMonster = "SwitchMonster",
}
