// What an icon says rather than which glyph draws it, so a feature never names an icon set
export enum UiIconMeaning {
  Achievement = "Achievement",
  Bookmark = "Bookmark",
  Collapse = "Collapse",
  Command = "Command",
  Copy = "Copy",
  Device = "Device",
  Disclosure = "Disclosure",
  Dropdown = "Dropdown",
  Edit = "Edit",
  Expand = "Expand",
  Failure = "Failure",
  Info = "Info",
  Launcher = "Launcher",
  Menu = "Menu",
  More = "More",
  Next = "Next",
  Notifications = "Notifications",
  Previous = "Previous",
  Remove = "Remove",
  ResetView = "ResetView",
  ScrollToTop = "ScrollToTop",
  Search = "Search",
  SignIn = "SignIn",
  Success = "Success",
  Upload = "Upload",
  Warning = "Warning",
  ZoomIn = "ZoomIn",
  ZoomOut = "ZoomOut",
}
