// @unocss-include
import { UiIconMeaning } from "@/models/ui/UiIconMeaning";
import { UiStyle } from "@/models/ui/UiStyle";

// Each style's class for every meaning, written whole so the icons preset sees it. Voxel's is the pixel set first, and
// A Material Design Icons class for a meaning it has no glyph for
export const UiIconMap = {
  [UiStyle.Voxel]: {
    [UiIconMeaning.Achievement]: "i-pixelarticons:trophy",
    [UiIconMeaning.Bookmark]: "i-pixelarticons:bookmark",
    [UiIconMeaning.Chart]: "i-pixelarticons:chart-bar",
    [UiIconMeaning.ClearFilter]: "i-mdi:filter-off",
    [UiIconMeaning.Close]: "i-pixelarticons:close",
    [UiIconMeaning.Collapse]: "i-pixelarticons:collapse",
    [UiIconMeaning.Columns]: "i-pixelarticons:layout-columns",
    [UiIconMeaning.Command]: "i-pixelarticons:command",
    [UiIconMeaning.Comment]: "i-pixelarticons:comment",
    [UiIconMeaning.Copy]: "i-pixelarticons:copy",
    [UiIconMeaning.Create]: "i-pixelarticons:plus",
    [UiIconMeaning.Delete]: "i-pixelarticons:trash",
    [UiIconMeaning.Device]: "i-pixelarticons:monitor",
    [UiIconMeaning.Disclosure]: "i-pixelarticons:chevron-right",
    [UiIconMeaning.Downvote]: "i-pixelarticons:arrow-big-down",
    [UiIconMeaning.Drag]: "i-mdi:drag",
    [UiIconMeaning.Dropdown]: "i-pixelarticons:chevron-down",
    [UiIconMeaning.Edit]: "i-pixelarticons:pencil",
    [UiIconMeaning.Expand]: "i-pixelarticons:expand",
    [UiIconMeaning.Failure]: "i-pixelarticons:close",
    [UiIconMeaning.Favorite]: "i-pixelarticons:star",
    [UiIconMeaning.File]: "i-pixelarticons:file",
    [UiIconMeaning.Filter]: "i-pixelarticons:filter",
    [UiIconMeaning.Folder]: "i-pixelarticons:folder",
    [UiIconMeaning.Group]: "i-pixelarticons:list",
    [UiIconMeaning.Hide]: "i-pixelarticons:eye-closed",
    [UiIconMeaning.Info]: "i-pixelarticons:info-box",
    [UiIconMeaning.Launcher]: "i-pixelarticons:grid-3x3",
    [UiIconMeaning.Link]: "i-pixelarticons:link",
    [UiIconMeaning.Lock]: "i-pixelarticons:lock",
    [UiIconMeaning.Menu]: "i-pixelarticons:menu",
    [UiIconMeaning.More]: "i-pixelarticons:more-horizontal",
    [UiIconMeaning.Next]: "i-pixelarticons:chevron-right",
    [UiIconMeaning.Notifications]: "i-pixelarticons:bell",
    [UiIconMeaning.Previous]: "i-pixelarticons:chevron-left",
    [UiIconMeaning.Recent]: "i-pixelarticons:clock",
    [UiIconMeaning.Record]: "i-pixelarticons:mic",
    [UiIconMeaning.Redo]: "i-pixelarticons:redo",
    [UiIconMeaning.Refresh]: "i-pixelarticons:reload",
    [UiIconMeaning.Remove]: "i-pixelarticons:close",
    [UiIconMeaning.Reply]: "i-pixelarticons:reply",
    [UiIconMeaning.ResetView]: "i-pixelarticons:reload",
    [UiIconMeaning.Rows]: "i-pixelarticons:layout-rows",
    [UiIconMeaning.Save]: "i-pixelarticons:save",
    [UiIconMeaning.ScrollToTop]: "i-pixelarticons:arrow-up",
    [UiIconMeaning.Search]: "i-pixelarticons:search",
    [UiIconMeaning.Show]: "i-pixelarticons:eye",
    [UiIconMeaning.SignIn]: "i-pixelarticons:login",
    [UiIconMeaning.SortAscending]: "i-pixelarticons:arrow-up",
    [UiIconMeaning.SortDescending]: "i-pixelarticons:arrow-down",
    [UiIconMeaning.Stop]: "i-pixelarticons:stop",
    [UiIconMeaning.Storage]: "i-pixelarticons:database",
    [UiIconMeaning.Success]: "i-pixelarticons:check",
    [UiIconMeaning.Summary]: "i-pixelarticons:dashboard",
    [UiIconMeaning.Tools]: "i-pixelarticons:sliders",
    [UiIconMeaning.Undo]: "i-pixelarticons:undo",
    [UiIconMeaning.Upload]: "i-pixelarticons:upload",
    [UiIconMeaning.Upvote]: "i-pixelarticons:arrow-big-up",
    [UiIconMeaning.Warning]: "i-pixelarticons:warning-box",
    [UiIconMeaning.ZoomIn]: "i-pixelarticons:zoom-in",
    [UiIconMeaning.ZoomOut]: "i-pixelarticons:zoom-out",
  },
} as const satisfies Record<UiStyle, Record<UiIconMeaning, string>>;
