// @unocss-include
import { UiIconMeaning } from "@/models/ui/UiIconMeaning";

// The pixel set first, and a Material Design Icons class for a meaning it has no glyph for
export const UiIconMap = {
  [UiIconMeaning.Achievement]: "i-pixelarticons:trophy",
  [UiIconMeaning.Bookmark]: "i-pixelarticons:bookmark",
  [UiIconMeaning.Collapse]: "i-pixelarticons:collapse",
  [UiIconMeaning.Command]: "i-pixelarticons:command",
  [UiIconMeaning.Comment]: "i-pixelarticons:comment",
  [UiIconMeaning.Copy]: "i-pixelarticons:copy",
  [UiIconMeaning.Create]: "i-pixelarticons:plus",
  [UiIconMeaning.Delete]: "i-pixelarticons:trash",
  [UiIconMeaning.Device]: "i-pixelarticons:monitor",
  [UiIconMeaning.Disclosure]: "i-pixelarticons:chevron-right",
  [UiIconMeaning.Downvote]: "i-pixelarticons:arrow-big-down",
  [UiIconMeaning.Dropdown]: "i-pixelarticons:chevron-down",
  [UiIconMeaning.Edit]: "i-pixelarticons:pencil",
  [UiIconMeaning.Expand]: "i-pixelarticons:expand",
  [UiIconMeaning.Failure]: "i-pixelarticons:close",
  [UiIconMeaning.Info]: "i-pixelarticons:info-box",
  [UiIconMeaning.Launcher]: "i-pixelarticons:grid-3x3",
  [UiIconMeaning.Menu]: "i-pixelarticons:menu",
  [UiIconMeaning.More]: "i-pixelarticons:more-horizontal",
  [UiIconMeaning.Next]: "i-pixelarticons:chevron-right",
  [UiIconMeaning.Notifications]: "i-pixelarticons:bell",
  [UiIconMeaning.Previous]: "i-pixelarticons:chevron-left",
  [UiIconMeaning.Record]: "i-pixelarticons:mic",
  [UiIconMeaning.Remove]: "i-pixelarticons:close",
  [UiIconMeaning.Reply]: "i-pixelarticons:reply",
  [UiIconMeaning.ResetView]: "i-pixelarticons:reload",
  [UiIconMeaning.ScrollToTop]: "i-pixelarticons:arrow-up",
  [UiIconMeaning.Search]: "i-pixelarticons:search",
  [UiIconMeaning.SignIn]: "i-pixelarticons:login",
  [UiIconMeaning.Stop]: "i-pixelarticons:stop",
  [UiIconMeaning.Success]: "i-pixelarticons:check",
  [UiIconMeaning.Upload]: "i-pixelarticons:upload",
  [UiIconMeaning.Upvote]: "i-pixelarticons:arrow-big-up",
  [UiIconMeaning.Warning]: "i-pixelarticons:warning-box",
  [UiIconMeaning.ZoomIn]: "i-pixelarticons:zoom-in",
  [UiIconMeaning.ZoomOut]: "i-pixelarticons:zoom-out",
} as const satisfies Record<UiIconMeaning, string>;
