export enum MessageAchievementName {
  CenturyClub = "CenturyClub",
  Chatterbox = "Chatterbox",
  ConversationKeeper = "ConversationKeeper",
  EarlyBird = "EarlyBird",
  EmojiMaster = "EmojiMaster",
  EssayWriter = "EssayWriter",
  FileSharer = "FileSharer",
  FirstMessage = "FirstMessage",
  Gossip = "Gossip",
  LinkSharer = "LinkSharer",
  MessageEditor = "MessageEditor",
  MessageForwarder = "MessageForwarder",
  MessageMaster = "MessageMaster",
  NightOwl = "NightOwl",
  PinCollector = "PinCollector",
  SecondThoughts = "SecondThoughts",
  ShortAndSweet = "ShortAndSweet",
  Typist = "Typist",
  Unpinner = "Unpinner",
  Verbose = "Verbose",
}
