// Tiles are generated by a small pool of workers, a few at a time, and a few hundred are kept: about a view's worth
// Twice over, so turning back finds the ground still there
export const TERRAIN_WORKER_COUNT = 2;
export const MAX_PENDING_TILE_COUNT = 8;
export const MAX_CACHED_TILE_COUNT = 256;
// Room for a frame's wanted and drawn tiles, several times what a view selects
export const TILE_SELECTION_CAPACITY = 512;
// Past a kilometre from the scene's origin the world is moved back under the camera, in steps of a coarsest tile so
// Every tile edge stays on a whole number
export const ORIGIN_SHIFT_THRESHOLD = 1024;
export const ORIGIN_SHIFT_STEP = 512;
// The square of water kept under the camera, wide enough to reach past where the fog closes on every side
export const WATER_SURFACE_SIZE = 3200;
