// Tiles are generated by a small pool of workers, a few at a time, and a few hundred are kept: about a view's worth
// Twice over, so turning back finds the ground still there
export const TERRAIN_WORKER_COUNT = 2;
export const MAX_PENDING_TILE_COUNT = 8;
export const MAX_CACHED_TILE_COUNT = 256;
// Room for a frame's wanted and drawn tiles, several times what a view selects
export const TILE_SELECTION_CAPACITY = 512;
// Past a kilometre from the scene's origin the world is moved back under the camera, in steps of a coarsest tile so
// Every tile edge stays on a whole number
export const ORIGIN_SHIFT_THRESHOLD = 1024;
export const ORIGIN_SHIFT_STEP = 512;
// The square of water kept under the camera, wide enough to reach past where the fog closes on every side
export const WATER_SURFACE_SIZE = 3200;
// The ground the grass reads its footing from: a square past the middle ring's reach at a third of a metre a texel,
// Redrawn once the camera has crossed an eighth of it. A blade has a root, a middle and a tip
export const GRASS_CAPTURE_SIZE = 160;
export const GRASS_CAPTURE_RESOLUTION = 512;
export const GRASS_RECAPTURE_DISTANCE = 20;
export const GRASS_BLADE_SEGMENT_COUNT = 3;
// How far the clouds drift for a unit of wind, in cloud-layer units a second
export const CLOUD_DRIFT_PER_WIND = 0.012;
