import { AchievementCategory } from "#shared/models/achievement/AchievementCategory";
import { AchievementOperator } from "#shared/models/achievement/AchievementOperator";
import { AchievementConditionType } from "#shared/models/achievement/type/AchievementConditionType";
import { defineAchievementDefinition } from "#shared/services/achievement/defineAchievementDefinition";
import { BinaryOperator, MessageAchievementName } from "@esposter/db-schema";

export const MessageAchievementDefinitionMap = {
  [MessageAchievementName.CenturyClub]: defineAchievementDefinition({
    amount: 100,
    category: AchievementCategory.Message,
    description: "Send 100 messages",
    icon: "mdi-message",
    points: 100,
    triggerPath: "message.createMessage" as const,
  }),
  [MessageAchievementName.Chatterbox]: defineAchievementDefinition({
    amount: 500,
    category: AchievementCategory.Message,
    description: "Send 500 messages",
    icon: "mdi-message-processing",
    points: 250,
    triggerPath: "message.createMessage" as const,
  }),
  [MessageAchievementName.ConversationKeeper]: defineAchievementDefinition({
    amount: 50,
    category: AchievementCategory.Message,
    condition: {
      operator: BinaryOperator.ne,
      path: "replyRowKey",
      type: AchievementConditionType.Property,
      value: undefined,
    },
    description: "Reply to 50 messages",
    icon: "mdi-reply",
    points: 75,
    triggerPath: "message.createMessage" as const,
  }),
  [MessageAchievementName.EarlyBird]: defineAchievementDefinition({
    category: AchievementCategory.Message,
    condition: {
      max: 7,
      min: 5,
      referenceUnit: "day",
      type: AchievementConditionType.Time,
      unit: "hour",
    },
    description: "Send a message between 5-7 AM",
    icon: "mdi-weather-sunset-up",
    points: 25,
    triggerPath: "message.createMessage" as const,
  }),
  [MessageAchievementName.EssayWriter]: defineAchievementDefinition({
    category: AchievementCategory.Message,
    condition: {
      operator: BinaryOperator.ge,
      path: "message.length",
      type: AchievementConditionType.Property,
      value: 1000,
    },
    description: "Send a message with over 1,000 characters",
    icon: "mdi-text-long",
    points: 40,
    triggerPath: "message.createMessage" as const,
  }),
  [MessageAchievementName.FileSharer]: defineAchievementDefinition({
    amount: 1,
    category: AchievementCategory.Message,
    condition: {
      operator: BinaryOperator.gt,
      path: "files.length",
      type: AchievementConditionType.Property,
      value: 0,
    },
    description: "Share your first file",
    icon: "mdi-file-upload",
    points: 20,
    triggerPath: "message.createMessage" as const,
  }),
  [MessageAchievementName.FirstMessage]: defineAchievementDefinition({
    amount: 1,
    category: AchievementCategory.Message,
    description: "Send your first message",
    icon: "mdi-message-text",
    points: 10,
    triggerPath: "message.createMessage" as const,
  }),
  [MessageAchievementName.Gossip]: defineAchievementDefinition({
    amount: 50,
    category: AchievementCategory.Message,
    description: "Forward 50 messages",
    icon: "mdi-share-variant",
    points: 100,
    triggerPath: "message.forwardMessage" as const,
  }),
  [MessageAchievementName.LinkSharer]: defineAchievementDefinition({
    amount: 1,
    category: AchievementCategory.Message,
    condition: {
      operator: AchievementOperator.Contains,
      path: "message",
      type: AchievementConditionType.Property,
      value: "http",
    },
    description: "Share a URL in a message",
    icon: "mdi-link-variant",
    points: 10,
    triggerPath: "message.createMessage" as const,
  }),
  [MessageAchievementName.MessageEditor]: defineAchievementDefinition({
    amount: 1,
    category: AchievementCategory.Message,
    description: "Edit a message",
    icon: "mdi-message-draw",
    points: 5,
    triggerPath: "message.updateMessage" as const,
  }),
  [MessageAchievementName.MessageForwarder]: defineAchievementDefinition({
    amount: 1,
    category: AchievementCategory.Message,
    description: "Forward a message to another room",
    icon: "mdi-share",
    points: 15,
    triggerPath: "message.forwardMessage" as const,
  }),
  [MessageAchievementName.MessageMaster]: defineAchievementDefinition({
    amount: 1000,
    category: AchievementCategory.Message,
    description: "Send 1,000 messages",
    icon: "mdi-message-star",
    points: 500,
    triggerPath: "message.createMessage" as const,
  }),
  [MessageAchievementName.NightOwl]: defineAchievementDefinition({
    category: AchievementCategory.Message,
    condition: {
      max: 5,
      min: 0,
      referenceUnit: "day",
      type: AchievementConditionType.Time,
      unit: "hour",
    },
    description: "Send a message between midnight and 5 AM",
    icon: "mdi-weather-night",
    points: 30,
    triggerPath: "message.createMessage" as const,
  }),
  [MessageAchievementName.PinCollector]: defineAchievementDefinition({
    amount: 10,
    category: AchievementCategory.Message,
    description: "Pin 10 important messages",
    icon: "mdi-pin",
    points: 50,
    triggerPath: "message.pinMessage" as const,
  }),
  [MessageAchievementName.SecondThoughts]: defineAchievementDefinition({
    amount: 10,
    category: AchievementCategory.Message,
    description: "Delete 10 of your own messages",
    icon: "mdi-delete",
    points: 20,
    triggerPath: "message.deleteMessage" as const,
  }),
  [MessageAchievementName.ShortAndSweet]: defineAchievementDefinition({
    amount: 100,
    category: AchievementCategory.Message,
    condition: {
      operator: BinaryOperator.lt,
      path: "message.length",
      type: AchievementConditionType.Property,
      value: 10,
    },
    description: "Send 100 messages under 10 characters",
    icon: "mdi-message-flash",
    points: 50,
    triggerPath: "message.createMessage" as const,
  }),
  [MessageAchievementName.Typist]: defineAchievementDefinition({
    amount: 100,
    category: AchievementCategory.Message,
    description: "Start typing 100 times",
    icon: "mdi-keyboard",
    points: 10,
    triggerPath: "message.createTyping" as const,
  }),
  [MessageAchievementName.Unpinner]: defineAchievementDefinition({
    amount: 1,
    category: AchievementCategory.Message,
    description: "Unpin a message",
    icon: "mdi-pin-off",
    points: 5,
    triggerPath: "message.unpinMessage" as const,
  }),
  [MessageAchievementName.Verbose]: defineAchievementDefinition({
    amount: 50,
    category: AchievementCategory.Message,
    condition: {
      operator: BinaryOperator.ge,
      path: "message.length",
      type: AchievementConditionType.Property,
      value: 500,
    },
    description: "Send 50 messages with 500-999 characters",
    icon: "mdi-text",
    points: 75,
    triggerPath: "message.createMessage" as const,
  }),
};
