name: Build & Lint
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: npm i
      - name: Build Nuxt 3
        run: npm run build
      - name: Run ESLint
        run: npm run lint
