name: 🏗️ CI

on:
  push:
    branches:
      - "**"

jobs:
  build:
    name: Build
    runs-on: blacksmith-2vcpu-ubuntu-2404
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: 🔧 Setup Project Dependencies
        uses: ./.github/actions/setup-project-dependencies

      - name: 📦 Install dependencies
        run: pnpm i

      - name: 🏗️ Build
        run: pnpm build

  lint:
    name: Lint
    runs-on: blacksmith-2vcpu-ubuntu-2404
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: 🔧 Setup Project Dependencies
        uses: ./.github/actions/setup-project-dependencies

      - name: 📦 Install dependencies
        run: pnpm i

      - name: 🔍 Lint
        run: pnpm lint

  format:
    name: Format
    runs-on: blacksmith-2vcpu-ubuntu-2404
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: 🔧 Setup Project Dependencies
        uses: ./.github/actions/setup-project-dependencies

      - name: 📦 Install dependencies
        run: pnpm i

      - name: 📝 Format
        run: pnpm format:check

  typecheck:
    name: Typecheck
    runs-on: blacksmith-2vcpu-ubuntu-2404
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: 🔧 Setup Project Dependencies
        uses: ./.github/actions/setup-project-dependencies

      - name: 📦 Install dependencies
        run: pnpm i

      - name: ✅ Typecheck
        run: pnpm typecheck

  coverage:
    name: Coverage
    runs-on: blacksmith-2vcpu-ubuntu-2404
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: 🔧 Setup Project Dependencies
        uses: ./.github/actions/setup-project-dependencies

      - name: 📦 Install dependencies
        run: pnpm i

      - name: 🧪 Test
        run: pnpm coverage

      - name: 📊 Upload Coverage
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: coverage
          path: packages/app/coverage
          if-no-files-found: error
