name: Lint
# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ESLint
        run: npm run lint
